// hermaphrodite gap jn asymmetric.cpp
//---------------------------------------------------------------------------

#pragma hdrstop

#include "hermaphrodite gap jn asymmetric.cpp"
//---------------------------------------------------------------------------
#pragma package(smart_init)

// This is the full C Elegans Connectome as defined in:
// SI 5 Connectome adjacency matrices, corr July 2020.xlsm

//469 static declarations for TNeurons with Synapses
    
enum Category {
    cat_PHARYNX,
    cat_SENSORY_NEURONS,
    cat_INTERNEURONS,
    cat_MOTOR_NEURONS,
    cat_SEXSPECIFIC_CELLS
 };

enum SubCategory {
    sub__7,
    sub__6,
    sub__5,
    sub__4,
    sub__3,
    sub__2,
    sub__1,
    sub__4,
    sub__3,
    sub__2,
    sub__1,
    sub__0,
    sub_HEAD_MOTOR_NEURONS,
    sub_SUBLATERAL_MOTOR_NEURONS,
    sub_VENTRAL_CORD_MOTOR_NEURONS,
    sub_BODYWALL_MUSCLES,
    sub_OTHER_END_ORGANS,
    sub_MOTOR_NEURONS,
    sub_MUSCLES
};

TNeuron I1L("I1L ", cat_PHARYNX, sub__7 );
TNeuron I1R("I1R ", cat_PHARYNX, sub__7 );
TNeuron I2L("I2L ", cat_PHARYNX, sub__7 );
TNeuron I2R("I2R ", cat_PHARYNX, sub__7 );
TNeuron I3("I3 ", cat_PHARYNX, sub__7 );
TNeuron I4("I4 ", cat_PHARYNX, sub__7 );
TNeuron I5("I5 ", cat_PHARYNX, sub__7 );
TNeuron I6("I6 ", cat_PHARYNX, sub__7 );
TNeuron M1("M1 ", cat_PHARYNX, sub__7 );
TNeuron M2L("M2L ", cat_PHARYNX, sub__7 );
TNeuron M2R("M2R ", cat_PHARYNX, sub__7 );
TNeuron M3L("M3L ", cat_PHARYNX, sub__7 );
TNeuron M3R("M3R ", cat_PHARYNX, sub__7 );
TNeuron M4("M4 ", cat_PHARYNX, sub__7 );
TNeuron M5("M5 ", cat_PHARYNX, sub__7 );
TNeuron MCL("MCL ", cat_PHARYNX, sub__7 );
TNeuron MCR("MCR ", cat_PHARYNX, sub__7 );
TNeuron MI("MI ", cat_PHARYNX, sub__7 );
TNeuron NSML("NSML ", cat_PHARYNX, sub__7 );
TNeuron NSMR("NSMR ", cat_PHARYNX, sub__7 );
TNeuron pm1("pm1 ", cat_PHARYNX, sub__7 );
TNeuron pm2D("pm2D ", cat_PHARYNX, sub__7 );
TNeuron pm2VL("pm2VL ", cat_PHARYNX, sub__7 );
TNeuron pm2VR("pm2VR ", cat_PHARYNX, sub__7 );
TNeuron pm3D("pm3D ", cat_PHARYNX, sub__7 );
TNeuron pm3VL("pm3VL ", cat_PHARYNX, sub__7 );
TNeuron pm3VR("pm3VR ", cat_PHARYNX, sub__7 );
TNeuron pm4D("pm4D ", cat_PHARYNX, sub__7 );
TNeuron pm4VL("pm4VL ", cat_PHARYNX, sub__7 );
TNeuron pm4VR("pm4VR ", cat_PHARYNX, sub__7 );
TNeuron pm5D("pm5D ", cat_PHARYNX, sub__7 );
TNeuron pm5VL("pm5VL ", cat_PHARYNX, sub__7 );
TNeuron pm5VR("pm5VR ", cat_PHARYNX, sub__7 );
TNeuron pm6D("pm6D ", cat_PHARYNX, sub__7 );
TNeuron pm6VL("pm6VL ", cat_PHARYNX, sub__7 );
TNeuron pm6VR("pm6VR ", cat_PHARYNX, sub__7 );
TNeuron pm7D("pm7D ", cat_PHARYNX, sub__7 );
TNeuron pm7VL("pm7VL ", cat_PHARYNX, sub__7 );
TNeuron pm7VR("pm7VR ", cat_PHARYNX, sub__7 );
TNeuron pm8("pm8 ", cat_PHARYNX, sub__7 );
TNeuron mc1DL("mc1DL ", cat_PHARYNX, sub__7 );
TNeuron mc1DR("mc1DR ", cat_PHARYNX, sub__7 );
TNeuron mc1V("mc1V ", cat_PHARYNX, sub__7 );
TNeuron mc2DL("mc2DL ", cat_PHARYNX, sub__7 );
TNeuron mc2DR("mc2DR ", cat_PHARYNX, sub__7 );
TNeuron mc2V("mc2V ", cat_PHARYNX, sub__7 );
TNeuron mc3DL("mc3DL ", cat_PHARYNX, sub__7 );
TNeuron mc3DR("mc3DR ", cat_PHARYNX, sub__7 );
TNeuron mc3V("mc3V ", cat_PHARYNX, sub__7 );
TNeuron e2D("e2D ", cat_PHARYNX, sub__7 );
TNeuron e2VL("e2VL ", cat_PHARYNX, sub__7 );
TNeuron e2VR("e2VR ", cat_PHARYNX, sub__7 );
TNeuron e3D("e3D ", cat_PHARYNX, sub__7 );
TNeuron e3VL("e3VL ", cat_PHARYNX, sub__7 );
TNeuron e3VR("e3VR ", cat_PHARYNX, sub__7 );
TNeuron g1AL("g1AL ", cat_PHARYNX, sub__7 );
TNeuron g1AR("g1AR ", cat_PHARYNX, sub__7 );
TNeuron ASIL("ASIL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASIR("ASIR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASJL("ASJL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASJR("ASJR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWAL("AWAL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWAR("AWAR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASGL("ASGL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASGR("ASGR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWBL("AWBL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWBR("AWBR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASEL("ASEL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASER("ASER ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ADFL("ADFL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ADFR("ADFR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AFDL("AFDL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AFDR("AFDR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWCL("AWCL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron AWCR("AWCR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASKL("ASKL ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASKR("ASKR ", cat_SENSORY_NEURONS, sub__6 );
TNeuron ASHL("ASHL ", cat_SENSORY_NEURONS, sub__5 );
TNeuron ASHR("ASHR ", cat_SENSORY_NEURONS, sub__5 );
TNeuron ADLL("ADLL ", cat_SENSORY_NEURONS, sub__5 );
TNeuron ADLR("ADLR ", cat_SENSORY_NEURONS, sub__5 );
TNeuron BAGL("BAGL ", cat_SENSORY_NEURONS, sub__4 );
TNeuron BAGR("BAGR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron URXL("URXL ", cat_SENSORY_NEURONS, sub__4 );
TNeuron URXR("URXR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron ALNL("ALNL ", cat_SENSORY_NEURONS, sub__4 );
TNeuron ALNR("ALNR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron PLNL("PLNL ", cat_SENSORY_NEURONS, sub__4 );
TNeuron PLNR("PLNR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron SDQL("SDQL ", cat_SENSORY_NEURONS, sub__4 );
TNeuron SDQR("SDQR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron AQR("AQR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron PQR("PQR ", cat_SENSORY_NEURONS, sub__4 );
TNeuron ALML("ALML ", cat_SENSORY_NEURONS, sub__3 );
TNeuron ALMR("ALMR ", cat_SENSORY_NEURONS, sub__3 );
TNeuron AVM("AVM ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PVM("PVM ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PLML("PLML ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PLMR("PLMR ", cat_SENSORY_NEURONS, sub__3 );
TNeuron FLPL("FLPL ", cat_SENSORY_NEURONS, sub__3 );
TNeuron FLPR("FLPR ", cat_SENSORY_NEURONS, sub__3 );
TNeuron DVA("DVA ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PVDL("PVDL ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PVDR("PVDR ", cat_SENSORY_NEURONS, sub__3 );
TNeuron ADEL("ADEL ", cat_SENSORY_NEURONS, sub__3 );
TNeuron ADER("ADER ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PDEL("PDEL ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PDER("PDER ", cat_SENSORY_NEURONS, sub__3 );
TNeuron PHAL("PHAL ", cat_SENSORY_NEURONS, sub__2 );
TNeuron PHAR("PHAR ", cat_SENSORY_NEURONS, sub__2 );
TNeuron PHBL("PHBL ", cat_SENSORY_NEURONS, sub__2 );
TNeuron PHBR("PHBR ", cat_SENSORY_NEURONS, sub__2 );
TNeuron PHCL("PHCL ", cat_SENSORY_NEURONS, sub__2 );
TNeuron PHCR("PHCR ", cat_SENSORY_NEURONS, sub__2 );
TNeuron IL2DL("IL2DL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL2DR("IL2DR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL2L("IL2L ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL2R("IL2R ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL2VL("IL2VL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL2VR("IL2VR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron CEPDL("CEPDL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron CEPDR("CEPDR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron CEPVL("CEPVL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron CEPVR("CEPVR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron URYDL("URYDL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron URYDR("URYDR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron URYVL("URYVL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron URYVR("URYVR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLLL("OLLL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLLR("OLLR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLQDL("OLQDL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLQDR("OLQDR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLQVL("OLQVL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron OLQVR("OLQVR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1DL("IL1DL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1DR("IL1DR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1L("IL1L ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1R("IL1R ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1VL("IL1VL ", cat_SENSORY_NEURONS, sub__1 );
TNeuron IL1VR("IL1VR ", cat_SENSORY_NEURONS, sub__1 );
TNeuron AINL("AINL ", cat_INTERNEURONS, sub__4 );
TNeuron AINR("AINR ", cat_INTERNEURONS, sub__4 );
TNeuron AIML("AIML ", cat_INTERNEURONS, sub__4 );
TNeuron AIMR("AIMR ", cat_INTERNEURONS, sub__4 );
TNeuron RIH("RIH ", cat_INTERNEURONS, sub__4 );
TNeuron URBL("URBL ", cat_INTERNEURONS, sub__4 );
TNeuron URBR("URBR ", cat_INTERNEURONS, sub__4 );
TNeuron RIR("RIR ", cat_INTERNEURONS, sub__4 );
TNeuron AIYL("AIYL ", cat_INTERNEURONS, sub__3 );
TNeuron AIYR("AIYR ", cat_INTERNEURONS, sub__3 );
TNeuron AIAL("AIAL ", cat_INTERNEURONS, sub__3 );
TNeuron AIAR("AIAR ", cat_INTERNEURONS, sub__3 );
TNeuron AUAL("AUAL ", cat_INTERNEURONS, sub__3 );
TNeuron AUAR("AUAR ", cat_INTERNEURONS, sub__3 );
TNeuron AIZL("AIZL ", cat_INTERNEURONS, sub__3 );
TNeuron AIZR("AIZR ", cat_INTERNEURONS, sub__3 );
TNeuron RIS("RIS ", cat_INTERNEURONS, sub__3 );
TNeuron ALA("ALA ", cat_INTERNEURONS, sub__3 );
TNeuron PVQL("PVQL ", cat_INTERNEURONS, sub__3 );
TNeuron PVQR("PVQR ", cat_INTERNEURONS, sub__3 );
TNeuron ADAL("ADAL ", cat_INTERNEURONS, sub__3 );
TNeuron ADAR("ADAR ", cat_INTERNEURONS, sub__3 );
TNeuron RIFL("RIFL ", cat_INTERNEURONS, sub__3 );
TNeuron RIFR("RIFR ", cat_INTERNEURONS, sub__3 );
TNeuron BDUL("BDUL ", cat_INTERNEURONS, sub__3 );
TNeuron BDUR("BDUR ", cat_INTERNEURONS, sub__3 );
TNeuron PVR("PVR ", cat_INTERNEURONS, sub__3 );
TNeuron AVFL("AVFL ", cat_INTERNEURONS, sub__3 );
TNeuron AVFR("AVFR ", cat_INTERNEURONS, sub__3 );
TNeuron AVHL("AVHL ", cat_INTERNEURONS, sub__3 );
TNeuron AVHR("AVHR ", cat_INTERNEURONS, sub__3 );
TNeuron PVPL("PVPL ", cat_INTERNEURONS, sub__3 );
TNeuron PVPR("PVPR ", cat_INTERNEURONS, sub__3 );
TNeuron LUAL("LUAL ", cat_INTERNEURONS, sub__3 );
TNeuron LUAR("LUAR ", cat_INTERNEURONS, sub__3 );
TNeuron PVNL("PVNL ", cat_INTERNEURONS, sub__3 );
TNeuron PVNR("PVNR ", cat_INTERNEURONS, sub__3 );
TNeuron AVG("AVG ", cat_INTERNEURONS, sub__3 );
TNeuron DVB("DVB ", cat_INTERNEURONS, sub__3 );
TNeuron RIBL("RIBL ", cat_INTERNEURONS, sub__2 );
TNeuron RIBR("RIBR ", cat_INTERNEURONS, sub__2 );
TNeuron RIGL("RIGL ", cat_INTERNEURONS, sub__2 );
TNeuron RIGR("RIGR ", cat_INTERNEURONS, sub__2 );
TNeuron RMGL("RMGL ", cat_INTERNEURONS, sub__2 );
TNeuron RMGR("RMGR ", cat_INTERNEURONS, sub__2 );
TNeuron AIBL("AIBL ", cat_INTERNEURONS, sub__2 );
TNeuron AIBR("AIBR ", cat_INTERNEURONS, sub__2 );
TNeuron RICL("RICL ", cat_INTERNEURONS, sub__2 );
TNeuron RICR("RICR ", cat_INTERNEURONS, sub__2 );
TNeuron SAADL("SAADL ", cat_INTERNEURONS, sub__2 );
TNeuron SAADR("SAADR ", cat_INTERNEURONS, sub__2 );
TNeuron SAAVL("SAAVL ", cat_INTERNEURONS, sub__2 );
TNeuron SAAVR("SAAVR ", cat_INTERNEURONS, sub__2 );
TNeuron AVKL("AVKL ", cat_INTERNEURONS, sub__2 );
TNeuron AVKR("AVKR ", cat_INTERNEURONS, sub__2 );
TNeuron DVC("DVC ", cat_INTERNEURONS, sub__2 );
TNeuron AVJL("AVJL ", cat_INTERNEURONS, sub__2 );
TNeuron AVJR("AVJR ", cat_INTERNEURONS, sub__2 );
TNeuron PVT("PVT ", cat_INTERNEURONS, sub__2 );
TNeuron AVDL("AVDL ", cat_INTERNEURONS, sub__2 );
TNeuron AVDR("AVDR ", cat_INTERNEURONS, sub__2 );
TNeuron AVL("AVL ", cat_INTERNEURONS, sub__2 );
TNeuron PVWL("PVWL ", cat_INTERNEURONS, sub__2 );
TNeuron PVWR("PVWR ", cat_INTERNEURONS, sub__2 );
TNeuron RIAL("RIAL ", cat_INTERNEURONS, sub__1 );
TNeuron RIAR("RIAR ", cat_INTERNEURONS, sub__1 );
TNeuron RIML("RIML ", cat_INTERNEURONS, sub__1 );
TNeuron RIMR("RIMR ", cat_INTERNEURONS, sub__1 );
TNeuron AVEL("AVEL ", cat_INTERNEURONS, sub__1 );
TNeuron AVER("AVER ", cat_INTERNEURONS, sub__1 );
TNeuron RMFL("RMFL ", cat_INTERNEURONS, sub__1 );
TNeuron RMFR("RMFR ", cat_INTERNEURONS, sub__1 );
TNeuron RID("RID ", cat_INTERNEURONS, sub__1 );
TNeuron AVBL("AVBL ", cat_INTERNEURONS, sub__1 );
TNeuron AVBR("AVBR ", cat_INTERNEURONS, sub__1 );
TNeuron AVAL("AVAL ", cat_INTERNEURONS, sub__1 );
TNeuron AVAR("AVAR ", cat_INTERNEURONS, sub__1 );
TNeuron PVCL("PVCL ", cat_INTERNEURONS, sub__1 );
TNeuron PVCR("PVCR ", cat_INTERNEURONS, sub__1 );
TNeuron RIPL("RIPL ", cat_INTERNEURONS, sub__0 );
TNeuron RIPR("RIPR ", cat_INTERNEURONS, sub__0 );
TNeuron URADL("URADL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron URADR("URADR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron URAVL("URAVL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron URAVR("URAVR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMEL("RMEL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMER("RMER ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMED("RMED ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMEV("RMEV ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDDL("RMDDL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDDR("RMDDR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDL("RMDL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDR("RMDR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDVL("RMDVL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMDVR("RMDVR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RIVL("RIVL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RIVR("RIVR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMHL("RMHL ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron RMHR("RMHR ", cat_MOTOR_NEURONS, sub_HEAD_MOTOR_NEURONS );
TNeuron SABD("SABD ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SABVL("SABVL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SABVR("SABVR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMDDL("SMDDL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMDDR("SMDDR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMDVL("SMDVL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMDVR("SMDVR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMBDL("SMBDL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMBDR("SMBDR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMBVL("SMBVL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SMBVR("SMBVR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIBDL("SIBDL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIBDR("SIBDR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIBVL("SIBVL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIBVR("SIBVR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIADL("SIADL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIADR("SIADR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIAVL("SIAVL ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron SIAVR("SIAVR ", cat_MOTOR_NEURONS, sub_SUBLATERAL_MOTOR_NEURONS );
TNeuron DA01("DA01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA02("DA02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA03("DA03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA04("DA04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA05("DA05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA06("DA06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA07("DA07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA08("DA08 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DA09("DA09 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron PDA("PDA ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB01("DB01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB02("DB02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB03("DB03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB04("DB04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB05("DB05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB06("DB06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DB07("DB07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS01("AS01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS02("AS02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS03("AS03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS04("AS04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS05("AS05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS06("AS06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS07("AS07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS08("AS08 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS09("AS09 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS10("AS10 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron AS11("AS11 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron PDB("PDB ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD01("DD01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD02("DD02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD03("DD03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD04("DD04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD05("DD05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron DD06("DD06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA01("VA01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA02("VA02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA03("VA03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA04("VA04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA05("VA05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA06("VA06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA07("VA07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA08("VA08 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA09("VA09 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA10("VA10 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA11("VA11 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VA12("VA12 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB01("VB01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB02("VB02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB03("VB03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB04("VB04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB05("VB05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB06("VB06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB07("VB07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB08("VB08 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB09("VB09 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB10("VB10 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VB11("VB11 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD01("VD01 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD02("VD02 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD03("VD03 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD04("VD04 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD05("VD05 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD06("VD06 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD07("VD07 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD08("VD08 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD09("VD09 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD10("VD10 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD11("VD11 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD12("VD12 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron VD13("VD13 ", cat_MOTOR_NEURONS, sub_VENTRAL_CORD_MOTOR_NEURONS );
TNeuron dBWML1("dBWML1 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML2("dBWML2 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML3("dBWML3 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML4("dBWML4 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML5("dBWML5 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML6("dBWML6 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML7("dBWML7 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR1("dBWMR1 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR2("dBWMR2 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR3("dBWMR3 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR4("dBWMR4 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR5("dBWMR5 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR6("dBWMR6 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR7("dBWMR7 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML1("vBWML1 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML2("vBWML2 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML3("vBWML3 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML4("vBWML4 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML5("vBWML5 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML6("vBWML6 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML7("vBWML7 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR1("vBWMR1 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR2("vBWMR2 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR3("vBWMR3 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR4("vBWMR4 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR5("vBWMR5 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR6("vBWMR6 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR7("vBWMR7 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML8("dBWML8 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML9("dBWML9 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML10("dBWML10 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML11("dBWML11 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML12("dBWML12 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML13("dBWML13 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML14("dBWML14 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML15("dBWML15 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML16("dBWML16 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML17("dBWML17 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML18("dBWML18 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML19("dBWML19 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML20("dBWML20 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML21("dBWML21 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML22("dBWML22 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML23("dBWML23 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWML24("dBWML24 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR8("dBWMR8 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR9("dBWMR9 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR10("dBWMR10 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR11("dBWMR11 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR12("dBWMR12 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR13("dBWMR13 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR14("dBWMR14 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR15("dBWMR15 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR16("dBWMR16 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR17("dBWMR17 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR18("dBWMR18 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR19("dBWMR19 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR20("dBWMR20 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR21("dBWMR21 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR22("dBWMR22 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR23("dBWMR23 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron dBWMR24("dBWMR24 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML8("vBWML8 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML9("vBWML9 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML10("vBWML10 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML11("vBWML11 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML12("vBWML12 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML13("vBWML13 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML14("vBWML14 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML15("vBWML15 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML16("vBWML16 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML17("vBWML17 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML18("vBWML18 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML19("vBWML19 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML20("vBWML20 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML21("vBWML21 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML22("vBWML22 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWML23("vBWML23 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR8("vBWMR8 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR9("vBWMR9 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR10("vBWMR10 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR11("vBWMR11 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR12("vBWMR12 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR13("vBWMR13 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR14("vBWMR14 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR15("vBWMR15 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR16("vBWMR16 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR17("vBWMR17 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR18("vBWMR18 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR19("vBWMR19 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR20("vBWMR20 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR21("vBWMR21 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR22("vBWMR22 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR23("vBWMR23 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron vBWMR24("vBWMR24 ", cat_MOTOR_NEURONS, sub_BODYWALL_MUSCLES );
TNeuron CEPshDL("CEPshDL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron CEPshDR("CEPshDR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron CEPshVL("CEPshVL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron CEPshVR("CEPshVR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRDL("GLRDL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRDR("GLRDR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRL("GLRL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRR("GLRR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRVL("GLRVL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron GLRVR("GLRVR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron CANL("CANL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron CANR("CANR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron exc_cell("exc_cell ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron exc_gl("exc_gl ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron hmc("hmc ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron hyp("hyp ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron intern("intern ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron mu_intL("mu_intL ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron mu_intR("mu_intR ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron mu_anal("mu_anal ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron mu_sph("mu_sph ", cat_MOTOR_NEURONS, sub_OTHER_END_ORGANS );
TNeuron HSNL("HSNL ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron HSNR("HSNR ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC01("VC01 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC02("VC02 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC03("VC03 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC04("VC04 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC05("VC05 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron VC06("VC06 ", cat_SEXSPECIFIC_CELLS, sub_MOTOR_NEURONS );
TNeuron um2AL("um2AL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um2AR("um2AR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um1AL("um1AL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um1AR("um1AR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um1PL("um1PL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um1PR("um1PR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um2PL("um2PL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron um2PR("um2PR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm2AL("vm2AL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm2AR("vm2AR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm1AL("vm1AL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm1AR("vm1AR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm1PL("vm1PL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm1PR("vm1PR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm2PL("vm2PL ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
TNeuron vm2PR("vm2PR ", cat_SEXSPECIFIC_CELLS, sub_MUSCLES );
// Adding all Neurons to the container class Neurons
void TConnectome::setupNeurons()
{
    Neurons.Add( &I1L );
    Neurons.Add( &I1R );
    Neurons.Add( &I2L );
    Neurons.Add( &I2R );
    Neurons.Add( &I3 );
    Neurons.Add( &I4 );
    Neurons.Add( &I5 );
    Neurons.Add( &I6 );
    Neurons.Add( &M1 );
    Neurons.Add( &M2L );
    Neurons.Add( &M2R );
    Neurons.Add( &M3L );
    Neurons.Add( &M3R );
    Neurons.Add( &M4 );
    Neurons.Add( &M5 );
    Neurons.Add( &MCL );
    Neurons.Add( &MCR );
    Neurons.Add( &MI );
    Neurons.Add( &NSML );
    Neurons.Add( &NSMR );
    Neurons.Add( &pm1 );
    Neurons.Add( &pm2D );
    Neurons.Add( &pm2VL );
    Neurons.Add( &pm2VR );
    Neurons.Add( &pm3D );
    Neurons.Add( &pm3VL );
    Neurons.Add( &pm3VR );
    Neurons.Add( &pm4D );
    Neurons.Add( &pm4VL );
    Neurons.Add( &pm4VR );
    Neurons.Add( &pm5D );
    Neurons.Add( &pm5VL );
    Neurons.Add( &pm5VR );
    Neurons.Add( &pm6D );
    Neurons.Add( &pm6VL );
    Neurons.Add( &pm6VR );
    Neurons.Add( &pm7D );
    Neurons.Add( &pm7VL );
    Neurons.Add( &pm7VR );
    Neurons.Add( &pm8 );
    Neurons.Add( &mc1DL );
    Neurons.Add( &mc1DR );
    Neurons.Add( &mc1V );
    Neurons.Add( &mc2DL );
    Neurons.Add( &mc2DR );
    Neurons.Add( &mc2V );
    Neurons.Add( &mc3DL );
    Neurons.Add( &mc3DR );
    Neurons.Add( &mc3V );
    Neurons.Add( &e2D );
    Neurons.Add( &e2VL );
    Neurons.Add( &e2VR );
    Neurons.Add( &e3D );
    Neurons.Add( &e3VL );
    Neurons.Add( &e3VR );
    Neurons.Add( &g1AL );
    Neurons.Add( &g1AR );
    Neurons.Add( &ASIL );
    Neurons.Add( &ASIR );
    Neurons.Add( &ASJL );
    Neurons.Add( &ASJR );
    Neurons.Add( &AWAL );
    Neurons.Add( &AWAR );
    Neurons.Add( &ASGL );
    Neurons.Add( &ASGR );
    Neurons.Add( &AWBL );
    Neurons.Add( &AWBR );
    Neurons.Add( &ASEL );
    Neurons.Add( &ASER );
    Neurons.Add( &ADFL );
    Neurons.Add( &ADFR );
    Neurons.Add( &AFDL );
    Neurons.Add( &AFDR );
    Neurons.Add( &AWCL );
    Neurons.Add( &AWCR );
    Neurons.Add( &ASKL );
    Neurons.Add( &ASKR );
    Neurons.Add( &ASHL );
    Neurons.Add( &ASHR );
    Neurons.Add( &ADLL );
    Neurons.Add( &ADLR );
    Neurons.Add( &BAGL );
    Neurons.Add( &BAGR );
    Neurons.Add( &URXL );
    Neurons.Add( &URXR );
    Neurons.Add( &ALNL );
    Neurons.Add( &ALNR );
    Neurons.Add( &PLNL );
    Neurons.Add( &PLNR );
    Neurons.Add( &SDQL );
    Neurons.Add( &SDQR );
    Neurons.Add( &AQR );
    Neurons.Add( &PQR );
    Neurons.Add( &ALML );
    Neurons.Add( &ALMR );
    Neurons.Add( &AVM );
    Neurons.Add( &PVM );
    Neurons.Add( &PLML );
    Neurons.Add( &PLMR );
    Neurons.Add( &FLPL );
    Neurons.Add( &FLPR );
    Neurons.Add( &DVA );
    Neurons.Add( &PVDL );
    Neurons.Add( &PVDR );
    Neurons.Add( &ADEL );
    Neurons.Add( &ADER );
    Neurons.Add( &PDEL );
    Neurons.Add( &PDER );
    Neurons.Add( &PHAL );
    Neurons.Add( &PHAR );
    Neurons.Add( &PHBL );
    Neurons.Add( &PHBR );
    Neurons.Add( &PHCL );
    Neurons.Add( &PHCR );
    Neurons.Add( &IL2DL );
    Neurons.Add( &IL2DR );
    Neurons.Add( &IL2L );
    Neurons.Add( &IL2R );
    Neurons.Add( &IL2VL );
    Neurons.Add( &IL2VR );
    Neurons.Add( &CEPDL );
    Neurons.Add( &CEPDR );
    Neurons.Add( &CEPVL );
    Neurons.Add( &CEPVR );
    Neurons.Add( &URYDL );
    Neurons.Add( &URYDR );
    Neurons.Add( &URYVL );
    Neurons.Add( &URYVR );
    Neurons.Add( &OLLL );
    Neurons.Add( &OLLR );
    Neurons.Add( &OLQDL );
    Neurons.Add( &OLQDR );
    Neurons.Add( &OLQVL );
    Neurons.Add( &OLQVR );
    Neurons.Add( &IL1DL );
    Neurons.Add( &IL1DR );
    Neurons.Add( &IL1L );
    Neurons.Add( &IL1R );
    Neurons.Add( &IL1VL );
    Neurons.Add( &IL1VR );
    Neurons.Add( &AINL );
    Neurons.Add( &AINR );
    Neurons.Add( &AIML );
    Neurons.Add( &AIMR );
    Neurons.Add( &RIH );
    Neurons.Add( &URBL );
    Neurons.Add( &URBR );
    Neurons.Add( &RIR );
    Neurons.Add( &AIYL );
    Neurons.Add( &AIYR );
    Neurons.Add( &AIAL );
    Neurons.Add( &AIAR );
    Neurons.Add( &AUAL );
    Neurons.Add( &AUAR );
    Neurons.Add( &AIZL );
    Neurons.Add( &AIZR );
    Neurons.Add( &RIS );
    Neurons.Add( &ALA );
    Neurons.Add( &PVQL );
    Neurons.Add( &PVQR );
    Neurons.Add( &ADAL );
    Neurons.Add( &ADAR );
    Neurons.Add( &RIFL );
    Neurons.Add( &RIFR );
    Neurons.Add( &BDUL );
    Neurons.Add( &BDUR );
    Neurons.Add( &PVR );
    Neurons.Add( &AVFL );
    Neurons.Add( &AVFR );
    Neurons.Add( &AVHL );
    Neurons.Add( &AVHR );
    Neurons.Add( &PVPL );
    Neurons.Add( &PVPR );
    Neurons.Add( &LUAL );
    Neurons.Add( &LUAR );
    Neurons.Add( &PVNL );
    Neurons.Add( &PVNR );
    Neurons.Add( &AVG );
    Neurons.Add( &DVB );
    Neurons.Add( &RIBL );
    Neurons.Add( &RIBR );
    Neurons.Add( &RIGL );
    Neurons.Add( &RIGR );
    Neurons.Add( &RMGL );
    Neurons.Add( &RMGR );
    Neurons.Add( &AIBL );
    Neurons.Add( &AIBR );
    Neurons.Add( &RICL );
    Neurons.Add( &RICR );
    Neurons.Add( &SAADL );
    Neurons.Add( &SAADR );
    Neurons.Add( &SAAVL );
    Neurons.Add( &SAAVR );
    Neurons.Add( &AVKL );
    Neurons.Add( &AVKR );
    Neurons.Add( &DVC );
    Neurons.Add( &AVJL );
    Neurons.Add( &AVJR );
    Neurons.Add( &PVT );
    Neurons.Add( &AVDL );
    Neurons.Add( &AVDR );
    Neurons.Add( &AVL );
    Neurons.Add( &PVWL );
    Neurons.Add( &PVWR );
    Neurons.Add( &RIAL );
    Neurons.Add( &RIAR );
    Neurons.Add( &RIML );
    Neurons.Add( &RIMR );
    Neurons.Add( &AVEL );
    Neurons.Add( &AVER );
    Neurons.Add( &RMFL );
    Neurons.Add( &RMFR );
    Neurons.Add( &RID );
    Neurons.Add( &AVBL );
    Neurons.Add( &AVBR );
    Neurons.Add( &AVAL );
    Neurons.Add( &AVAR );
    Neurons.Add( &PVCL );
    Neurons.Add( &PVCR );
    Neurons.Add( &RIPL );
    Neurons.Add( &RIPR );
    Neurons.Add( &URADL );
    Neurons.Add( &URADR );
    Neurons.Add( &URAVL );
    Neurons.Add( &URAVR );
    Neurons.Add( &RMEL );
    Neurons.Add( &RMER );
    Neurons.Add( &RMED );
    Neurons.Add( &RMEV );
    Neurons.Add( &RMDDL );
    Neurons.Add( &RMDDR );
    Neurons.Add( &RMDL );
    Neurons.Add( &RMDR );
    Neurons.Add( &RMDVL );
    Neurons.Add( &RMDVR );
    Neurons.Add( &RIVL );
    Neurons.Add( &RIVR );
    Neurons.Add( &RMHL );
    Neurons.Add( &RMHR );
    Neurons.Add( &SABD );
    Neurons.Add( &SABVL );
    Neurons.Add( &SABVR );
    Neurons.Add( &SMDDL );
    Neurons.Add( &SMDDR );
    Neurons.Add( &SMDVL );
    Neurons.Add( &SMDVR );
    Neurons.Add( &SMBDL );
    Neurons.Add( &SMBDR );
    Neurons.Add( &SMBVL );
    Neurons.Add( &SMBVR );
    Neurons.Add( &SIBDL );
    Neurons.Add( &SIBDR );
    Neurons.Add( &SIBVL );
    Neurons.Add( &SIBVR );
    Neurons.Add( &SIADL );
    Neurons.Add( &SIADR );
    Neurons.Add( &SIAVL );
    Neurons.Add( &SIAVR );
    Neurons.Add( &DA01 );
    Neurons.Add( &DA02 );
    Neurons.Add( &DA03 );
    Neurons.Add( &DA04 );
    Neurons.Add( &DA05 );
    Neurons.Add( &DA06 );
    Neurons.Add( &DA07 );
    Neurons.Add( &DA08 );
    Neurons.Add( &DA09 );
    Neurons.Add( &PDA );
    Neurons.Add( &DB01 );
    Neurons.Add( &DB02 );
    Neurons.Add( &DB03 );
    Neurons.Add( &DB04 );
    Neurons.Add( &DB05 );
    Neurons.Add( &DB06 );
    Neurons.Add( &DB07 );
    Neurons.Add( &AS01 );
    Neurons.Add( &AS02 );
    Neurons.Add( &AS03 );
    Neurons.Add( &AS04 );
    Neurons.Add( &AS05 );
    Neurons.Add( &AS06 );
    Neurons.Add( &AS07 );
    Neurons.Add( &AS08 );
    Neurons.Add( &AS09 );
    Neurons.Add( &AS10 );
    Neurons.Add( &AS11 );
    Neurons.Add( &PDB );
    Neurons.Add( &DD01 );
    Neurons.Add( &DD02 );
    Neurons.Add( &DD03 );
    Neurons.Add( &DD04 );
    Neurons.Add( &DD05 );
    Neurons.Add( &DD06 );
    Neurons.Add( &VA01 );
    Neurons.Add( &VA02 );
    Neurons.Add( &VA03 );
    Neurons.Add( &VA04 );
    Neurons.Add( &VA05 );
    Neurons.Add( &VA06 );
    Neurons.Add( &VA07 );
    Neurons.Add( &VA08 );
    Neurons.Add( &VA09 );
    Neurons.Add( &VA10 );
    Neurons.Add( &VA11 );
    Neurons.Add( &VA12 );
    Neurons.Add( &VB01 );
    Neurons.Add( &VB02 );
    Neurons.Add( &VB03 );
    Neurons.Add( &VB04 );
    Neurons.Add( &VB05 );
    Neurons.Add( &VB06 );
    Neurons.Add( &VB07 );
    Neurons.Add( &VB08 );
    Neurons.Add( &VB09 );
    Neurons.Add( &VB10 );
    Neurons.Add( &VB11 );
    Neurons.Add( &VD01 );
    Neurons.Add( &VD02 );
    Neurons.Add( &VD03 );
    Neurons.Add( &VD04 );
    Neurons.Add( &VD05 );
    Neurons.Add( &VD06 );
    Neurons.Add( &VD07 );
    Neurons.Add( &VD08 );
    Neurons.Add( &VD09 );
    Neurons.Add( &VD10 );
    Neurons.Add( &VD11 );
    Neurons.Add( &VD12 );
    Neurons.Add( &VD13 );
    Neurons.Add( &dBWML1 );
    Neurons.Add( &dBWML2 );
    Neurons.Add( &dBWML3 );
    Neurons.Add( &dBWML4 );
    Neurons.Add( &dBWML5 );
    Neurons.Add( &dBWML6 );
    Neurons.Add( &dBWML7 );
    Neurons.Add( &dBWMR1 );
    Neurons.Add( &dBWMR2 );
    Neurons.Add( &dBWMR3 );
    Neurons.Add( &dBWMR4 );
    Neurons.Add( &dBWMR5 );
    Neurons.Add( &dBWMR6 );
    Neurons.Add( &dBWMR7 );
    Neurons.Add( &vBWML1 );
    Neurons.Add( &vBWML2 );
    Neurons.Add( &vBWML3 );
    Neurons.Add( &vBWML4 );
    Neurons.Add( &vBWML5 );
    Neurons.Add( &vBWML6 );
    Neurons.Add( &vBWML7 );
    Neurons.Add( &vBWMR1 );
    Neurons.Add( &vBWMR2 );
    Neurons.Add( &vBWMR3 );
    Neurons.Add( &vBWMR4 );
    Neurons.Add( &vBWMR5 );
    Neurons.Add( &vBWMR6 );
    Neurons.Add( &vBWMR7 );
    Neurons.Add( &dBWML8 );
    Neurons.Add( &dBWML9 );
    Neurons.Add( &dBWML10 );
    Neurons.Add( &dBWML11 );
    Neurons.Add( &dBWML12 );
    Neurons.Add( &dBWML13 );
    Neurons.Add( &dBWML14 );
    Neurons.Add( &dBWML15 );
    Neurons.Add( &dBWML16 );
    Neurons.Add( &dBWML17 );
    Neurons.Add( &dBWML18 );
    Neurons.Add( &dBWML19 );
    Neurons.Add( &dBWML20 );
    Neurons.Add( &dBWML21 );
    Neurons.Add( &dBWML22 );
    Neurons.Add( &dBWML23 );
    Neurons.Add( &dBWML24 );
    Neurons.Add( &dBWMR8 );
    Neurons.Add( &dBWMR9 );
    Neurons.Add( &dBWMR10 );
    Neurons.Add( &dBWMR11 );
    Neurons.Add( &dBWMR12 );
    Neurons.Add( &dBWMR13 );
    Neurons.Add( &dBWMR14 );
    Neurons.Add( &dBWMR15 );
    Neurons.Add( &dBWMR16 );
    Neurons.Add( &dBWMR17 );
    Neurons.Add( &dBWMR18 );
    Neurons.Add( &dBWMR19 );
    Neurons.Add( &dBWMR20 );
    Neurons.Add( &dBWMR21 );
    Neurons.Add( &dBWMR22 );
    Neurons.Add( &dBWMR23 );
    Neurons.Add( &dBWMR24 );
    Neurons.Add( &vBWML8 );
    Neurons.Add( &vBWML9 );
    Neurons.Add( &vBWML10 );
    Neurons.Add( &vBWML11 );
    Neurons.Add( &vBWML12 );
    Neurons.Add( &vBWML13 );
    Neurons.Add( &vBWML14 );
    Neurons.Add( &vBWML15 );
    Neurons.Add( &vBWML16 );
    Neurons.Add( &vBWML17 );
    Neurons.Add( &vBWML18 );
    Neurons.Add( &vBWML19 );
    Neurons.Add( &vBWML20 );
    Neurons.Add( &vBWML21 );
    Neurons.Add( &vBWML22 );
    Neurons.Add( &vBWML23 );
    Neurons.Add( &vBWMR8 );
    Neurons.Add( &vBWMR9 );
    Neurons.Add( &vBWMR10 );
    Neurons.Add( &vBWMR11 );
    Neurons.Add( &vBWMR12 );
    Neurons.Add( &vBWMR13 );
    Neurons.Add( &vBWMR14 );
    Neurons.Add( &vBWMR15 );
    Neurons.Add( &vBWMR16 );
    Neurons.Add( &vBWMR17 );
    Neurons.Add( &vBWMR18 );
    Neurons.Add( &vBWMR19 );
    Neurons.Add( &vBWMR20 );
    Neurons.Add( &vBWMR21 );
    Neurons.Add( &vBWMR22 );
    Neurons.Add( &vBWMR23 );
    Neurons.Add( &vBWMR24 );
    Neurons.Add( &CEPshDL );
    Neurons.Add( &CEPshDR );
    Neurons.Add( &CEPshVL );
    Neurons.Add( &CEPshVR );
    Neurons.Add( &GLRDL );
    Neurons.Add( &GLRDR );
    Neurons.Add( &GLRL );
    Neurons.Add( &GLRR );
    Neurons.Add( &GLRVL );
    Neurons.Add( &GLRVR );
    Neurons.Add( &CANL );
    Neurons.Add( &CANR );
    Neurons.Add( &exc_cell );
    Neurons.Add( &exc_gl );
    Neurons.Add( &hmc );
    Neurons.Add( &hyp );
    Neurons.Add( &intern );
    Neurons.Add( &mu_intL );
    Neurons.Add( &mu_intR );
    Neurons.Add( &mu_anal );
    Neurons.Add( &mu_sph );
    Neurons.Add( &HSNL );
    Neurons.Add( &HSNR );
    Neurons.Add( &VC01 );
    Neurons.Add( &VC02 );
    Neurons.Add( &VC03 );
    Neurons.Add( &VC04 );
    Neurons.Add( &VC05 );
    Neurons.Add( &VC06 );
    Neurons.Add( &um2AL );
    Neurons.Add( &um2AR );
    Neurons.Add( &um1AL );
    Neurons.Add( &um1AR );
    Neurons.Add( &um1PL );
    Neurons.Add( &um1PR );
    Neurons.Add( &um2PL );
    Neurons.Add( &um2PR );
    Neurons.Add( &vm2AL );
    Neurons.Add( &vm2AR );
    Neurons.Add( &vm1AL );
    Neurons.Add( &vm1AR );
    Neurons.Add( &vm1PL );
    Neurons.Add( &vm1PR );
    Neurons.Add( &vm2PL );
    Neurons.Add( &vm2PR );
}
// Total 469 Neurons added

// Defines the 1450 Synapses
void TConnectome::setupSynapses()
{
    I1L.AddSynapse(&I2L, 2 );  
    I1L.AddSynapse(&M3L, 2 );  
    I1L.AddSynapse(&MCR, 1 );  
    I1L.AddSynapse(&NSML, 3 );  
    I1L.AddSynapse(&pm4VL, 1 );  
    I1L.AddSynapse(&RIPL, 2 );  
    I1R.AddSynapse(&I2R, 1 );  
    I1R.AddSynapse(&I3, 1 );  
    I1R.AddSynapse(&MCR, 4 );  
    I1R.AddSynapse(&NSMR, 2 );  
    I1R.AddSynapse(&pm3VR, 3 );  
    I1R.AddSynapse(&pm4VR, 2 );  
    I1R.AddSynapse(&RIPR, 2 );  
    I2L.AddSynapse(&I4, 1 );  
    I2L.AddSynapse(&M2L, 1 );  
    I2L.AddSynapse(&e3VL, 2 );  
    I2R.AddSynapse(&M1, 1 );  
    I2R.AddSynapse(&M2R, 1 );  
    I2R.AddSynapse(&MCR, 1 );  
    I2R.AddSynapse(&NSMR, 2 );  
    I2R.AddSynapse(&e3VR, 1 );  
    I3.AddSynapse(&M1, 1 );  
    I3.AddSynapse(&M2R, 1 );  
    I3.AddSynapse(&MI, 1 );  
    I3.AddSynapse(&pm4D, 3 );  
    I3.AddSynapse(&pm5D, 1 );  
    I4.AddSynapse(&M2R, 2 );  
    I4.AddSynapse(&M4, 1 );  
    I4.AddSynapse(&pm5VL, 1 );  
    I5.AddSynapse(&M2L, 1 );  
    I5.AddSynapse(&M2R, 1 );  
    I5.AddSynapse(&M5, 1 );  
    I5.AddSynapse(&g1AL, 4 );  
    I5.AddSynapse(&g1AR, 2 );  
    I6.AddSynapse(&M4, 5 );  
    M1.AddSynapse(&pm5D, 3 );  
    M2L.AddSynapse(&M4, 1 );  
    M2L.AddSynapse(&MCL, 1 );  
    M2L.AddSynapse(&pm4VL, 1 );  
    M2L.AddSynapse(&pm5VL, 1 );  
    M2L.AddSynapse(&g1AL, 2 );  
    M2R.AddSynapse(&M3R, 1 );  
    M2R.AddSynapse(&MCR, 11 );  
    M2R.AddSynapse(&MI, 5 );  
    M2R.AddSynapse(&pm5D, 1 );  
    M2R.AddSynapse(&g1AR, 2 );  
    M3L.AddSynapse(&NSMR, 1 );  
    M3L.AddSynapse(&pm4D, 2 );  
    M3L.AddSynapse(&pm5D, 1 );  
    M3L.AddSynapse(&pm5VL, 1 );  
    M3L.AddSynapse(&g1AL, 2 );  
    M3R.AddSynapse(&NSMR, 2 );  
    M3R.AddSynapse(&pm4VR, 1 );  
    M3R.AddSynapse(&pm5D, 1 );  
    M3R.AddSynapse(&pm5VR, 1 );  
    M3R.AddSynapse(&g1AR, 5 );  
    M4.AddSynapse(&M4, 1 );  
    M4.AddSynapse(&M5, 2 );  
    M4.AddSynapse(&pm5D, 1 );  
    M4.AddSynapse(&pm5VL, 1 );  
    M4.AddSynapse(&pm5VR, 1 );  
    M4.AddSynapse(&g1AL, 7 );  
    M4.AddSynapse(&g1AR, 2 );  
    M5.AddSynapse(&M5, 1 );  
    M5.AddSynapse(&pm5VL, 2 );  
    M5.AddSynapse(&pm6VL, 2 );  
    M5.AddSynapse(&pm6VR, 2 );  
    MI.AddSynapse(&pm4D, 3 );  
    NSML.AddSynapse(&NSMR, 2 );  
    NSMR.AddSynapse(&pm5D, 2 );  
    pm1.AddSynapse(&pm2D, 2 );  
    pm1.AddSynapse(&pm2VL, 2 );  
    pm1.AddSynapse(&pm2VR, 2 );  
    pm1.AddSynapse(&e3D, 4 );  
    pm2D.AddSynapse(&pm3D, 2 );  
    pm2VL.AddSynapse(&pm3VL, 2 );  
    pm2VR.AddSynapse(&pm3VR, 2 );  
    pm3D.AddSynapse(&pm4D, 2 );  
    pm3D.AddSynapse(&mc1DL, 2 );  
    pm3D.AddSynapse(&mc1DR, 2 );  
    pm3VL.AddSynapse(&pm4VL, 2 );  
    pm3VL.AddSynapse(&mc1DL, 2 );  
    pm3VL.AddSynapse(&mc1V, 2 );  
    pm3VL.AddSynapse(&e3VL, 4 );  
    pm3VR.AddSynapse(&pm4VR, 2 );  
    pm3VR.AddSynapse(&mc1V, 2 );  
    pm4D.AddSynapse(&pm5D, 2 );  
    pm4D.AddSynapse(&mc1DL, 2 );  
    pm4D.AddSynapse(&mc1DR, 2 );  
    pm4VL.AddSynapse(&pm5VL, 2 );  
    pm4VL.AddSynapse(&mc1DL, 2 );  
    pm4VL.AddSynapse(&mc1V, 2 );  
    pm4VR.AddSynapse(&pm5VR, 2 );  
    pm4VR.AddSynapse(&mc1DR, 4 );  
    pm4VR.AddSynapse(&mc1V, 2 );  
    pm5D.AddSynapse(&pm6D, 2 );  
    pm5D.AddSynapse(&mc2DL, 2 );  
    pm5D.AddSynapse(&mc2DR, 2 );  
    pm5VL.AddSynapse(&pm6VL, 2 );  
    pm5VL.AddSynapse(&mc2DL, 2 );  
    pm5VL.AddSynapse(&mc2V, 2 );  
    pm5VR.AddSynapse(&pm6VR, 2 );  
    pm5VR.AddSynapse(&mc2DR, 2 );  
    pm5VR.AddSynapse(&mc2V, 2 );  
    pm6D.AddSynapse(&mc3DL, 2 );  
    pm6D.AddSynapse(&mc3DR, 2 );  
    pm6VL.AddSynapse(&mc3DL, 2 );  
    pm6VL.AddSynapse(&mc3V, 2 );  
    pm6VR.AddSynapse(&mc3DR, 2 );  
    pm6VR.AddSynapse(&mc3V, 2 );  
    pm7D.AddSynapse(&pm8, 2 );  
    pm7D.AddSynapse(&mc3DL, 2 );  
    pm7D.AddSynapse(&mc3DR, 2 );  
    pm7VL.AddSynapse(&pm8, 2 );  
    pm7VL.AddSynapse(&mc3DL, 2 );  
    pm7VL.AddSynapse(&mc3V, 2 );  
    pm7VR.AddSynapse(&pm8, 2 );  
    pm7VR.AddSynapse(&mc3DR, 2 );  
    pm7VR.AddSynapse(&mc3V, 2 );  
    pm8.AddSynapse(&mc3DL, 2 );  
    pm8.AddSynapse(&mc3DR, 2 );  
    pm8.AddSynapse(&mc3V, 2 );  
    mc1DL.AddSynapse(&mc2DL, 2 );  
    mc1DR.AddSynapse(&mc2DR, 2 );  
    mc2DL.AddSynapse(&mc3DL, 2 );  
    mc2DR.AddSynapse(&mc3DR, 2 );  
    e2D.AddSynapse(&e3D, 2 );  
    e2VL.AddSynapse(&e3VL, 1 );  
    e2VR.AddSynapse(&e3D, 1 );  
    e2VR.AddSynapse(&e3VR, 1 );  
    ASIL.AddSynapse(&ASIR, 3 );  
    ASIL.AddSynapse(&AINR, 1 );  
    ASIL.AddSynapse(&AIAL, 1 );  
    ASIL.AddSynapse(&CEPshVL, 1 );  
    ASIR.AddSynapse(&ASGR, 4 );  
    ASIR.AddSynapse(&AIYR, 1 );  
    ASIR.AddSynapse(&AIAL, 2 );  
    ASIR.AddSynapse(&AIAR, 3 );  
    ASJL.AddSynapse(&ASJR, 7 );  
    ASJL.AddSynapse(&IL2L, 1 );  
    ASJL.AddSynapse(&AIAL, 1 );  
    ASJL.AddSynapse(&ALA, 2 );  
    ASJL.AddSynapse(&PVQL, 1 );  
    ASJL.AddSynapse(&SMDDR, 1 );  
    ASJR.AddSynapse(&AIMR, 1 );  
    ASJR.AddSynapse(&PVQR, 5 );  
    AWAL.AddSynapse(&AWAR, 2 );  
    AWAL.AddSynapse(&ADLL, 1 );  
    AWAL.AddSynapse(&AIAL, 1 );  
    AWAL.AddSynapse(&AIZL, 3 );  
    AWAR.AddSynapse(&ADFR, 3 );  
    AWAR.AddSynapse(&AIAR, 3 );  
    AWAR.AddSynapse(&AIZR, 3 );  
    ASGL.AddSynapse(&AWBL, 1 );  
    ASGL.AddSynapse(&ASEL, 3 );  
    ASGL.AddSynapse(&AINR, 1 );  
    ASGL.AddSynapse(&AIML, 1 );  
    ASGL.AddSynapse(&AIZL, 3 );  
    ASGL.AddSynapse(&SMDDR, 2 );  
    ASGR.AddSynapse(&ASER, 3 );  
    ASGR.AddSynapse(&ADFR, 1 );  
    ASGR.AddSynapse(&AWCR, 2 );  
    ASGR.AddSynapse(&ADLR, 1 );  
    ASGR.AddSynapse(&AINL, 1 );  
    ASGR.AddSynapse(&AIAR, 3 );  
    ASGR.AddSynapse(&AIZR, 1 );  
    AWBL.AddSynapse(&AWBR, 3 );  
    AWBL.AddSynapse(&AIAL, 1 );  
    AWBL.AddSynapse(&AUAL, 4 );  
    AWBL.AddSynapse(&RMGL, 1 );  
    AWBR.AddSynapse(&ASER, 1 );  
    AWBR.AddSynapse(&ADFR, 1 );  
    AWBR.AddSynapse(&AUAR, 3 );  
    AWBR.AddSynapse(&RMGR, 1 );  
    AWBR.AddSynapse(&RICL, 4 );  
    ASEL.AddSynapse(&AFDL, 6 );  
    ASEL.AddSynapse(&AFDR, 2 );  
    ASEL.AddSynapse(&AWCL, 1 );  
    ASEL.AddSynapse(&AWCR, 2 );  
    ASER.AddSynapse(&AFDR, 1 );  
    ASER.AddSynapse(&PVQR, 1 );  
    ASER.AddSynapse(&hyp, 1 );  
    ADFL.AddSynapse(&AFDL, 3 );  
    ADFL.AddSynapse(&AWCL, 1 );  
    ADFL.AddSynapse(&ASHL, 1 );  
    ADFL.AddSynapse(&URBL, 1 );  
    ADFL.AddSynapse(&AIZL, 1 );  
    ADFL.AddSynapse(&ADAL, 5 );  
    ADFL.AddSynapse(&RIAL, 1 );  
    ADFL.AddSynapse(&RIPL, 2 );  
    ADFL.AddSynapse(&GLRVR, 1 );  
    ADFL.AddSynapse(&exc_gl, 1 );  
    ADFR.AddSynapse(&AFDR, 5 );  
    ADFR.AddSynapse(&RIH, 1 );  
    ADFR.AddSynapse(&AIAR, 4 );  
    ADFR.AddSynapse(&ADAR, 4 );  
    ADFR.AddSynapse(&SMDVR, 2 );  
    ADFR.AddSynapse(&SMBVR, 1 );  
    ADFR.AddSynapse(&hyp, 2 );  
    AFDL.AddSynapse(&AFDR, 1 );  
    AFDL.AddSynapse(&URBL, 9 );  
    AFDL.AddSynapse(&AIYL, 2 );  
    AFDL.AddSynapse(&AIBL, 2 );  
    AFDL.AddSynapse(&AVEL, 1 );  
    AFDR.AddSynapse(&AWCR, 3 );  
    AFDR.AddSynapse(&ASHR, 4 );  
    AFDR.AddSynapse(&URBR, 2 );  
    AFDR.AddSynapse(&AIBR, 2 );  
    AFDR.AddSynapse(&RMDVR, 1 );  
    AWCL.AddSynapse(&AUAL, 1 );  
    AWCR.AddSynapse(&AIAL, 1 );  
    AWCR.AddSynapse(&AIAR, 1 );  
    ASKL.AddSynapse(&ASKR, 9 );  
    ASKL.AddSynapse(&ASHL, 18 );  
    ASKL.AddSynapse(&AIAL, 2 );  
    ASKL.AddSynapse(&PVQL, 8 );  
    ASKL.AddSynapse(&AVHL, 8 );  
    ASKL.AddSynapse(&AIBL, 1 );  
    ASKL.AddSynapse(&HSNL, 1 );  
    ASKR.AddSynapse(&ASKR, 2 );  
    ASKR.AddSynapse(&ASHR, 2 );  
    ASKR.AddSynapse(&ADLR, 1 );  
    ASKR.AddSynapse(&AIAR, 1 );  
    ASKR.AddSynapse(&ALA, 1 );  
    ASKR.AddSynapse(&PVQR, 25 );  
    ASKR.AddSynapse(&AVHR, 10 );  
    ASKR.AddSynapse(&RMGR, 1 );  
    ASKR.AddSynapse(&AIBR, 3 );  
    ASKR.AddSynapse(&HSNL, 3 );  
    ASKR.AddSynapse(&HSNR, 3 );  
    ASHL.AddSynapse(&ASHR, 7 );  
    ASHL.AddSynapse(&AIZL, 2 );  
    ASHL.AddSynapse(&ADAL, 2 );  
    ASHL.AddSynapse(&RMGL, 3 );  
    ASHL.AddSynapse(&RICL, 5 );  
    ASHR.AddSynapse(&AIAR, 1 );  
    ASHR.AddSynapse(&AIZR, 6 );  
    ASHR.AddSynapse(&ADAR, 3 );  
    ASHR.AddSynapse(&AVHL, 2 );  
    ASHR.AddSynapse(&RMGR, 3 );  
    ASHR.AddSynapse(&RICR, 4 );  
    ASHR.AddSynapse(&AVER, 1 );  
    ASHR.AddSynapse(&AVAR, 2 );  
    ADLL.AddSynapse(&ADLR, 6 );  
    ADLL.AddSynapse(&RMGL, 3 );  
    ADLL.AddSynapse(&AVDR, 2 );  
    ADLL.AddSynapse(&hyp, 1 );  
    BAGL.AddSynapse(&BAGR, 1 );  
    BAGL.AddSynapse(&AINR, 3 );  
    BAGL.AddSynapse(&RIR, 4 );  
    BAGL.AddSynapse(&RIGL, 1 );  
    BAGL.AddSynapse(&RIGR, 2 );  
    BAGR.AddSynapse(&RIR, 5 );  
    BAGR.AddSynapse(&AVEL, 1 );  
    URXL.AddSynapse(&IL2L, 1 );  
    URXL.AddSynapse(&RMGL, 3 );  
    URXR.AddSynapse(&IL2R, 4 );  
    URXR.AddSynapse(&AUAR, 3 );  
    URXR.AddSynapse(&RMGR, 5 );  
    URXR.AddSynapse(&RICR, 1 );  
    ALNL.AddSynapse(&SMDDR, 2 );  
    ALNL.AddSynapse(&SMDVL, 1 );  
    ALNL.AddSynapse(&SMBDR, 3 );  
    ALNL.AddSynapse(&hyp, 3 );  
    ALNR.AddSynapse(&ADER, 2 );  
    ALNR.AddSynapse(&PVR, 16 );  
    ALNR.AddSynapse(&RMGR, 1 );  
    ALNR.AddSynapse(&SMDDL, 1 );  
    PLNL.AddSynapse(&PHAL, 1 );  
    PLNL.AddSynapse(&PHBL, 1 );  
    PLNL.AddSynapse(&PHCL, 2 );  
    PLNR.AddSynapse(&PLMR, 1 );  
    PLNR.AddSynapse(&PHAR, 6 );  
    PLNR.AddSynapse(&VA02, 2 );  
    PLNR.AddSynapse(&hyp, 2 );  
    SDQL.AddSynapse(&SDQR, 2 );  
    SDQL.AddSynapse(&FLPL, 1 );  
    SDQL.AddSynapse(&DVA, 1 );  
    SDQL.AddSynapse(&SIADR, 1 );  
    SDQR.AddSynapse(&ALMR, 2 );  
    SDQR.AddSynapse(&DVA, 1 );  
    SDQR.AddSynapse(&AIBL, 1 );  
    SDQR.AddSynapse(&SAADL, 1 );  
    SDQR.AddSynapse(&AVBL, 1 );  
    SDQR.AddSynapse(&RIVL, 5 );  
    SDQR.AddSynapse(&RIVR, 3 );  
    SDQR.AddSynapse(&SIBVL, 2 );  
    SDQR.AddSynapse(&SIAVR, 1 );  
    AQR.AddSynapse(&PVPL, 41 );  
    AQR.AddSynapse(&PVPR, 61 );  
    AQR.AddSynapse(&RIGR, 3 );  
    AQR.AddSynapse(&AVKL, 7 );  
    AQR.AddSynapse(&AVKR, 2 );  
    AQR.AddSynapse(&AVBL, 3 );  
    PQR.AddSynapse(&PVPL, 16 );  
    PQR.AddSynapse(&PVPR, 10 );  
    PQR.AddSynapse(&PVNL, 3 );  
    PQR.AddSynapse(&PVNR, 2 );  
    PQR.AddSynapse(&AVJL, 5 );  
    PQR.AddSynapse(&AVJR, 2 );  
    PQR.AddSynapse(&AVDL, 2 );  
    PQR.AddSynapse(&AVDR, 3 );  
    PQR.AddSynapse(&AVAR, 17 );  
    PQR.AddSynapse(&PVCL, 2 );  
    PQR.AddSynapse(&hyp, 1 );  
    ALML.AddSynapse(&AVM, 7 );  
    ALML.AddSynapse(&PVR, 3 );  
    ALML.AddSynapse(&RMGL, 3 );  
    ALML.AddSynapse(&RMDDR, 2 );  
    ALML.AddSynapse(&SMBDR, 1 );  
    ALMR.AddSynapse(&AVM, 16 );  
    ALMR.AddSynapse(&PVR, 3 );  
    ALMR.AddSynapse(&AVDR, 2 );  
    AVM.AddSynapse(&PVR, 4 );  
    AVM.AddSynapse(&AVDL, 8 );  
    PVM.AddSynapse(&PVM, 1 );  
    PVM.AddSynapse(&DVA, 1 );  
    PVM.AddSynapse(&ADER, 1 );  
    PVM.AddSynapse(&PDEL, 11 );  
    PVM.AddSynapse(&PDER, 8 );  
    PVM.AddSynapse(&PVR, 1 );  
    PVM.AddSynapse(&AVKL, 1 );  
    PVM.AddSynapse(&DB03, 2 );  
    PVM.AddSynapse(&VD09, 1 );  
    PLML.AddSynapse(&PDEL, 2 );  
    PLML.AddSynapse(&PDER, 3 );  
    PLML.AddSynapse(&PVR, 15 );  
    PLML.AddSynapse(&LUAL, 8 );  
    PLML.AddSynapse(&AVDL, 3 );  
    PLML.AddSynapse(&AVDR, 2 );  
    PLML.AddSynapse(&AVAL, 2 );  
    PLML.AddSynapse(&AVAR, 3 );  
    PLML.AddSynapse(&PVCL, 4 );  
    PLML.AddSynapse(&hyp, 3 );  
    PLMR.AddSynapse(&PDEL, 4 );  
    PLMR.AddSynapse(&PDER, 2 );  
    PLMR.AddSynapse(&PVR, 3 );  
    PLMR.AddSynapse(&LUAR, 9 );  
    PLMR.AddSynapse(&AVAL, 1 );  
    PLMR.AddSynapse(&PVCR, 8 );  
    FLPL.AddSynapse(&FLPR, 6 );  
    FLPL.AddSynapse(&RIH, 1 );  
    FLPL.AddSynapse(&AIBL, 1 );  
    FLPL.AddSynapse(&AVDL, 5 );  
    FLPL.AddSynapse(&SIADR, 1 );  
    FLPL.AddSynapse(&DD01, 1 );  
    FLPR.AddSynapse(&ADER, 4 );  
    FLPR.AddSynapse(&AVDL, 9 );  
    FLPR.AddSynapse(&AVDR, 2 );  
    FLPR.AddSynapse(&DA01, 5 );  
    FLPR.AddSynapse(&DA02, 6 );  
    FLPR.AddSynapse(&DA03, 16 );  
    FLPR.AddSynapse(&AS01, 1 );  
    DVA.AddSynapse(&PDEL, 3 );  
    DVA.AddSynapse(&PDER, 6 );  
    DVA.AddSynapse(&PVR, 15 );  
    DVA.AddSynapse(&PVPL, 1 );  
    DVA.AddSynapse(&SAAVR, 1 );  
    DVA.AddSynapse(&AVKL, 18 );  
    DVA.AddSynapse(&DVC, 1 );  
    DVA.AddSynapse(&PVT, 8 );  
    DVA.AddSynapse(&AVBL, 11 );  
    DVA.AddSynapse(&AVBR, 3 );  
    DVA.AddSynapse(&PVCL, 3 );  
    DVA.AddSynapse(&PVCR, 1 );  
    DVA.AddSynapse(&SIADR, 1 );  
    DVA.AddSynapse(&SIAVR, 1 );  
    DVA.AddSynapse(&DA09, 3 );  
    DVA.AddSynapse(&PDA, 1 );  
    DVA.AddSynapse(&DB01, 3 );  
    DVA.AddSynapse(&DB07, 3 );  
    DVA.AddSynapse(&AS11, 1 );  
    DVA.AddSynapse(&VA11, 1 );  
    DVA.AddSynapse(&hyp, 4 );  
    PVDL.AddSynapse(&PVDR, 3 );  
    PVDL.AddSynapse(&ALA, 250 );  
    PVDL.AddSynapse(&AVG, 1 );  
    PVDL.AddSynapse(&AVAR, 4 );  
    PVDL.AddSynapse(&PVCR, 1 );  
    PVDL.AddSynapse(&DA03, 1 );  
    PVDL.AddSynapse(&DA05, 1 );  
    PVDL.AddSynapse(&DB01, 1 );  
    PVDL.AddSynapse(&VA10, 1 );  
    PVDL.AddSynapse(&CANL, 100 );  
    PVDL.AddSynapse(&hmc, 400 );  
    PVDL.AddSynapse(&hyp, 400 );  
    PVDR.AddSynapse(&PDER, 1 );  
    PVDR.AddSynapse(&ALA, 250 );  
    PVDR.AddSynapse(&DVC, 1 );  
    PVDR.AddSynapse(&AVAL, 6 );  
    PVDR.AddSynapse(&PVCR, 2 );  
    PVDR.AddSynapse(&AS03, 1 );  
    PVDR.AddSynapse(&VD09, 1 );  
    PVDR.AddSynapse(&CANR, 100 );  
    PVDR.AddSynapse(&hmc, 400 );  
    PVDR.AddSynapse(&hyp, 400 );  
    ADEL.AddSynapse(&IL2L, 2 );  
    ADEL.AddSynapse(&AINL, 2 );  
    ADEL.AddSynapse(&RIGR, 1 );  
    ADEL.AddSynapse(&RMER, 1 );  
    ADEL.AddSynapse(&RMDDR, 1 );  
    ADEL.AddSynapse(&SIBDL, 1 );  
    ADEL.AddSynapse(&SIBVL, 1 );  
    ADER.AddSynapse(&AINR, 4 );  
    ADER.AddSynapse(&PVQR, 2 );  
    ADER.AddSynapse(&AVKL, 4 );  
    ADER.AddSynapse(&AVJR, 1 );  
    PDEL.AddSynapse(&PDER, 25 );  
    PDEL.AddSynapse(&PVR, 8 );  
    PDEL.AddSynapse(&AVKR, 1 );  
    PDEL.AddSynapse(&PVCL, 2 );  
    PDEL.AddSynapse(&VB10, 1 );  
    PDEL.AddSynapse(&VD06, 2 );  
    PDER.AddSynapse(&PVR, 9 );  
    PDER.AddSynapse(&AVKL, 1 );  
    PDER.AddSynapse(&PVCL, 1 );  
    PDER.AddSynapse(&PVCR, 2 );  
    PDER.AddSynapse(&VB09, 7 );  
    PDER.AddSynapse(&VB10, 4 );  
    PDER.AddSynapse(&VD09, 5 );  
    PHAL.AddSynapse(&PHAR, 7 );  
    PHAL.AddSynapse(&PHCL, 1 );  
    PHAL.AddSynapse(&AVHL, 1 );  
    PHAL.AddSynapse(&PVPR, 7 );  
    PHAL.AddSynapse(&AVG, 3 );  
    PHAL.AddSynapse(&hyp, 1 );  
    PHAR.AddSynapse(&PHCR, 1 );  
    PHAR.AddSynapse(&PVR, 2 );  
    PHAR.AddSynapse(&AVHR, 2 );  
    PHAR.AddSynapse(&PVPL, 15 );  
    PHAR.AddSynapse(&AVG, 2 );  
    PHAR.AddSynapse(&PDA, 1 );  
    PHAR.AddSynapse(&hyp, 1 );  
    PHBL.AddSynapse(&PHBR, 17 );  
    PHBL.AddSynapse(&PVQL, 3 );  
    PHBL.AddSynapse(&AVHL, 1 );  
    PHBL.AddSynapse(&AVHR, 2 );  
    PHBL.AddSynapse(&AVJR, 1 );  
    PHBL.AddSynapse(&AVAR, 1 );  
    PHBL.AddSynapse(&PVCL, 3 );  
    PHBL.AddSynapse(&hyp, 3 );  
    PHBR.AddSynapse(&PHCR, 1 );  
    PHBR.AddSynapse(&AVHL, 10 );  
    PHBR.AddSynapse(&AVHR, 2 );  
    PHBR.AddSynapse(&PVPL, 1 );  
    PHBR.AddSynapse(&PVT, 1 );  
    PHBR.AddSynapse(&hyp, 4 );  
    PHCL.AddSynapse(&PHCR, 2 );  
    PHCL.AddSynapse(&AVAL, 1 );  
    PHCL.AddSynapse(&VA12, 1 );  
    PHCL.AddSynapse(&hyp, 1 );  
    PHCR.AddSynapse(&AVG, 1 );  
    PHCR.AddSynapse(&AVJR, 1 );  
    PHCR.AddSynapse(&AVAL, 3 );  
    PHCR.AddSynapse(&AVAR, 1 );  
    PHCR.AddSynapse(&PVCR, 5 );  
    PHCR.AddSynapse(&DA09, 7 );  
    IL2DL.AddSynapse(&URADL, 1 );  
    IL2DR.AddSynapse(&URADR, 1 );  
    IL2DR.AddSynapse(&RMED, 1 );  
    IL2L.AddSynapse(&OLLL, 2 );  
    IL2L.AddSynapse(&URBL, 4 );  
    IL2L.AddSynapse(&RMGL, 5 );  
    IL2L.AddSynapse(&URAVL, 1 );  
    IL2L.AddSynapse(&RMER, 2 );  
    IL2L.AddSynapse(&RMDL, 2 );  
    IL2R.AddSynapse(&URBR, 4 );  
    IL2R.AddSynapse(&RMGR, 1 );  
    IL2VL.AddSynapse(&URAVL, 3 );  
    IL2VR.AddSynapse(&CEPVR, 1 );  
    IL2VR.AddSynapse(&IL1VR, 1 );  
    CEPDL.AddSynapse(&OLQDL, 2 );  
    CEPDR.AddSynapse(&OLQDR, 8 );  
    CEPDR.AddSynapse(&GLRDL, 2 );  
    CEPDR.AddSynapse(&GLRDR, 2 );  
    CEPVL.AddSynapse(&OLQVL, 4 );  
    CEPVL.AddSynapse(&RIH, 1 );  
    CEPVL.AddSynapse(&URAVL, 3 );  
    CEPVL.AddSynapse(&CEPshVL, 1 );  
    CEPVR.AddSynapse(&OLQVR, 1 );  
    CEPVR.AddSynapse(&AIMR, 1 );  
    URYDL.AddSynapse(&RIGL, 4 );  
    URYDL.AddSynapse(&AVAL, 2 );  
    URYDR.AddSynapse(&RIGR, 3 );  
    URYDR.AddSynapse(&AVAR, 5 );  
    URYDR.AddSynapse(&URADR, 1 );  
    URYVL.AddSynapse(&RIGL, 3 );  
    URYVL.AddSynapse(&AVAR, 1 );  
    URYVR.AddSynapse(&AVAL, 2 );  
    OLLL.AddSynapse(&OLLR, 11 );  
    OLLL.AddSynapse(&RIGL, 3 );  
    OLLR.AddSynapse(&RIGR, 5 );  
    OLQDL.AddSynapse(&URBL, 3 );  
    OLQDL.AddSynapse(&RIBL, 5 );  
    OLQDL.AddSynapse(&RIGL, 3 );  
    OLQDL.AddSynapse(&RMDVL, 1 );  
    OLQDR.AddSynapse(&RIH, 2 );  
    OLQDR.AddSynapse(&URBR, 7 );  
    OLQDR.AddSynapse(&RIBR, 5 );  
    OLQDR.AddSynapse(&RIGR, 4 );  
    OLQDR.AddSynapse(&RMDVR, 1 );  
    OLQVL.AddSynapse(&ADAL, 4 );  
    OLQVL.AddSynapse(&RIBL, 2 );  
    OLQVL.AddSynapse(&RIGL, 2 );  
    OLQVL.AddSynapse(&RMDDL, 3 );  
    OLQVR.AddSynapse(&URBR, 5 );  
    OLQVR.AddSynapse(&RIBR, 6 );  
    OLQVR.AddSynapse(&RIGR, 6 );  
    OLQVR.AddSynapse(&RMDDR, 1 );  
    OLQVR.AddSynapse(&RMDVL, 2 );  
    OLQVR.AddSynapse(&RMHR, 1 );  
    IL1DL.AddSynapse(&IL1DR, 3 );  
    IL1DL.AddSynapse(&IL1L, 2 );  
    IL1DL.AddSynapse(&RMEV, 1 );  
    IL1DR.AddSynapse(&IL1R, 8 );  
    IL1DR.AddSynapse(&RMEV, 4 );  
    IL1DR.AddSynapse(&RMDVR, 1 );  
    IL1L.AddSynapse(&IL1VL, 8 );  
    IL1L.AddSynapse(&URBL, 2 );  
    IL1L.AddSynapse(&RIPL, 1 );  
    IL1L.AddSynapse(&RMER, 1 );  
    IL1R.AddSynapse(&IL1VR, 8 );  
    IL1VL.AddSynapse(&IL1VR, 11 );  
    IL1VL.AddSynapse(&RMED, 3 );  
    IL1VL.AddSynapse(&RMDDL, 1 );  
    IL1VR.AddSynapse(&URAVR, 4 );  
    AINL.AddSynapse(&AINR, 1 );  
    AINL.AddSynapse(&AUAR, 1 );  
    AINR.AddSynapse(&AUAL, 3 );  
    AINR.AddSynapse(&RIAL, 2 );  
    AIML.AddSynapse(&SIBDR, 2 );  
    AIMR.AddSynapse(&AVKR, 3 );  
    AIMR.AddSynapse(&SMBVR, 1 );  
    RIH.AddSynapse(&AIZL, 1 );  
    URBR.AddSynapse(&SMBVR, 1 );  
    AIYL.AddSynapse(&AIYR, 4 );  
    AIYL.AddSynapse(&AVKL, 1 );  
    AIYL.AddSynapse(&RIML, 5 );  
    AIYR.AddSynapse(&AUAR, 1 );  
    AIYR.AddSynapse(&RIMR, 3 );  
    AIAL.AddSynapse(&AIAR, 7 );  
    AIAL.AddSynapse(&AIBL, 5 );  
    AIAR.AddSynapse(&AIAR, 2 );  
    AUAL.AddSynapse(&AUAR, 2 );  
    AUAL.AddSynapse(&RMDVL, 2 );  
    AIZL.AddSynapse(&AIZR, 18 );  
    AIZL.AddSynapse(&RIGL, 1 );  
    AIZL.AddSynapse(&AIBR, 3 );  
    AIZR.AddSynapse(&AIBL, 4 );  
    RIS.AddSynapse(&AIBL, 1 );  
    RIS.AddSynapse(&AIBR, 3 );  
    RIS.AddSynapse(&AVJL, 15 );  
    RIS.AddSynapse(&RIML, 2 );  
    RIS.AddSynapse(&RIMR, 2 );  
    RIS.AddSynapse(&AVEL, 3 );  
    RIS.AddSynapse(&RMEV, 1 );  
    RIS.AddSynapse(&RMDR, 1 );  
    RIS.AddSynapse(&SMDDL, 2 );  
    RIS.AddSynapse(&SMDDR, 5 );  
    RIS.AddSynapse(&SMDVL, 2 );  
    ALA.AddSynapse(&AVER, 3 );  
    ALA.AddSynapse(&RID, 4 );  
    ALA.AddSynapse(&CANL, 401 );  
    ALA.AddSynapse(&CANR, 401 );  
    ALA.AddSynapse(&exc_cell, 100 );  
    ALA.AddSynapse(&exc_gl, 1 );  
    ALA.AddSynapse(&HSNL, 1 );  
    ALA.AddSynapse(&HSNR, 1 );  
    PVQL.AddSynapse(&PVQR, 46 );  
    PVQL.AddSynapse(&ADAL, 4 );  
    PVQL.AddSynapse(&AVFR, 2 );  
    PVQL.AddSynapse(&AVHR, 3 );  
    PVQL.AddSynapse(&PVPL, 8 );  
    PVQL.AddSynapse(&AVKR, 2 );  
    PVQL.AddSynapse(&DA08, 1 );  
    PVQL.AddSynapse(&hyp, 3 );  
    PVQR.AddSynapse(&ADAR, 2 );  
    PVQR.AddSynapse(&AVFL, 5 );  
    PVQR.AddSynapse(&AVHR, 2 );  
    PVQR.AddSynapse(&DVB, 1 );  
    PVQR.AddSynapse(&DVC, 7 );  
    PVQR.AddSynapse(&PVT, 1 );  
    PVQR.AddSynapse(&PVWR, 1 );  
    PVQR.AddSynapse(&PDA, 1 );  
    ADAL.AddSynapse(&ADAR, 3 );  
    ADAL.AddSynapse(&AVDR, 2 );  
    ADAR.AddSynapse(&AVDL, 3 );  
    RIFL.AddSynapse(&AVDL, 1 );  
    RIFL.AddSynapse(&AVER, 1 );  
    RIFL.AddSynapse(&VD01, 1 );  
    RIFL.AddSynapse(&HSNL, 1 );  
    RIFR.AddSynapse(&AVG, 3 );  
    RIFR.AddSynapse(&RMGR, 1 );  
    RIFR.AddSynapse(&AVJL, 1 );  
    RIFR.AddSynapse(&DD01, 2 );  
    BDUL.AddSynapse(&PVNL, 1 );  
    BDUR.AddSynapse(&PVR, 3 );  
    BDUR.AddSynapse(&HSNL, 1 );  
    BDUR.AddSynapse(&HSNR, 1 );  
    PVR.AddSynapse(&LUAL, 6 );  
    PVR.AddSynapse(&LUAR, 9 );  
    PVR.AddSynapse(&PVNR, 5 );  
    PVR.AddSynapse(&PVWR, 2 );  
    PVR.AddSynapse(&PVCR, 19 );  
    PVR.AddSynapse(&DA09, 15 );  
    PVR.AddSynapse(&DB07, 4 );  
    PVR.AddSynapse(&PDB, 13 );  
    PVR.AddSynapse(&VD13, 1 );  
    PVR.AddSynapse(&hyp, 12 );  
    AVFL.AddSynapse(&AVFR, 31 );  
    AVFL.AddSynapse(&AVHL, 4 );  
    AVFL.AddSynapse(&AVHR, 5 );  
    AVFL.AddSynapse(&PVPL, 2 );  
    AVFL.AddSynapse(&PVNR, 1 );  
    AVFL.AddSynapse(&AVG, 1 );  
    AVFL.AddSynapse(&PVCL, 1 );  
    AVFL.AddSynapse(&AS11, 2 );  
    AVFL.AddSynapse(&VD12, 3 );  
    AVFL.AddSynapse(&hyp, 8 );  
    AVFL.AddSynapse(&VC04, 1 );  
    AVFL.AddSynapse(&VC05, 1 );  
    AVFR.AddSynapse(&AVHL, 11 );  
    AVFR.AddSynapse(&AVHR, 7 );  
    AVFR.AddSynapse(&PVPL, 3 );  
    AVFR.AddSynapse(&RMGL, 1 );  
    AVFR.AddSynapse(&VB01, 1 );  
    AVFR.AddSynapse(&hyp, 3 );  
    AVFR.AddSynapse(&VC04, 1 );  
    AVFR.AddSynapse(&VC05, 1 );  
    AVHL.AddSynapse(&AVHR, 15 );  
    AVHL.AddSynapse(&PVPR, 6 );  
    AVHL.AddSynapse(&LUAL, 1 );  
    AVHL.AddSynapse(&PVNL, 1 );  
    AVHL.AddSynapse(&AVJR, 6 );  
    AVHL.AddSynapse(&AVDL, 2 );  
    AVHL.AddSynapse(&DB07, 3 );  
    AVHL.AddSynapse(&AS10, 1 );  
    AVHL.AddSynapse(&AS11, 3 );  
    AVHL.AddSynapse(&VD12, 8 );  
    AVHL.AddSynapse(&hyp, 35 );  
    AVHR.AddSynapse(&PVPL, 4 );  
    AVHR.AddSynapse(&PVPR, 3 );  
    AVHR.AddSynapse(&AVG, 4 );  
    AVHR.AddSynapse(&DVC, 4 );  
    AVHR.AddSynapse(&AVJL, 3 );  
    AVHR.AddSynapse(&AVJR, 2 );  
    AVHR.AddSynapse(&SIAVL, 1 );  
    AVHR.AddSynapse(&DA08, 5 );  
    AVHR.AddSynapse(&AS11, 17 );  
    AVHR.AddSynapse(&DD06, 1 );  
    AVHR.AddSynapse(&VD12, 13 );  
    AVHR.AddSynapse(&hyp, 11 );  
    PVPL.AddSynapse(&PVPL, 1 );  
    PVPL.AddSynapse(&PVPR, 2 );  
    PVPL.AddSynapse(&PVNL, 2 );  
    PVPL.AddSynapse(&AVG, 3 );  
    PVPL.AddSynapse(&DVB, 4 );  
    PVPL.AddSynapse(&RIGL, 2 );  
    PVPL.AddSynapse(&AIBR, 2 );  
    PVPL.AddSynapse(&AVKL, 3 );  
    PVPL.AddSynapse(&AVKR, 22 );  
    PVPL.AddSynapse(&DVC, 20 );  
    PVPL.AddSynapse(&PVT, 14 );  
    PVPL.AddSynapse(&AVL, 1 );  
    PVPL.AddSynapse(&AVAL, 1 );  
    PVPL.AddSynapse(&AS11, 6 );  
    PVPL.AddSynapse(&PDB, 1 );  
    PVPL.AddSynapse(&DD06, 2 );  
    PVPL.AddSynapse(&VA12, 1 );  
    PVPL.AddSynapse(&VD13, 11 );  
    PVPL.AddSynapse(&vBWML19, 2 );  
    PVPL.AddSynapse(&hyp, 47 );  
    PVPL.AddSynapse(&HSNL, 1 );  
    PVPR.AddSynapse(&PVNR, 2 );  
    PVPR.AddSynapse(&DVB, 4 );  
    PVPR.AddSynapse(&RMGR, 3 );  
    PVPR.AddSynapse(&AVKL, 6 );  
    PVPR.AddSynapse(&DVC, 34 );  
    PVPR.AddSynapse(&AVJL, 1 );  
    PVPR.AddSynapse(&PVT, 17 );  
    PVPR.AddSynapse(&AVL, 8 );  
    PVPR.AddSynapse(&PVWL, 1 );  
    PVPR.AddSynapse(&AVEL, 1 );  
    PVPR.AddSynapse(&AVAL, 2 );  
    PVPR.AddSynapse(&DD06, 9 );  
    PVPR.AddSynapse(&VD12, 35 );  
    PVPR.AddSynapse(&hyp, 4 );  
    PVPR.AddSynapse(&HSNR, 1 );  
    PVPR.AddSynapse(&VC01, 1 );  
    LUAL.AddSynapse(&PVNL, 3 );  
    LUAL.AddSynapse(&AVJL, 5 );  
    LUAL.AddSynapse(&AVAL, 2 );  
    LUAL.AddSynapse(&PVCL, 1 );  
    LUAR.AddSynapse(&PVNR, 2 );  
    LUAR.AddSynapse(&AVJL, 1 );  
    LUAR.AddSynapse(&AVJR, 1 );  
    LUAR.AddSynapse(&PVT, 4 );  
    LUAR.AddSynapse(&PVWL, 3 );  
    LUAR.AddSynapse(&PVWR, 3 );  
    LUAR.AddSynapse(&AVAL, 2 );  
    LUAR.AddSynapse(&AVAR, 4 );  
    PVNL.AddSynapse(&PVNR, 2 );  
    PVNL.AddSynapse(&AVJL, 5 );  
    PVNL.AddSynapse(&AVJR, 1 );  
    PVNL.AddSynapse(&PVT, 2 );  
    PVNL.AddSynapse(&AVDR, 1 );  
    PVNL.AddSynapse(&AVBR, 7 );  
    PVNL.AddSynapse(&AVAL, 1 );  
    PVNL.AddSynapse(&PVCL, 2 );  
    PVNL.AddSynapse(&hyp, 2 );  
    PVNR.AddSynapse(&DVC, 1 );  
    PVNR.AddSynapse(&AVJR, 5 );  
    PVNR.AddSynapse(&PVT, 3 );  
    PVNR.AddSynapse(&AVDL, 1 );  
    PVNR.AddSynapse(&AVDR, 1 );  
    PVNR.AddSynapse(&PVWR, 6 );  
    PVNR.AddSynapse(&AVBL, 5 );  
    PVNR.AddSynapse(&AVBR, 2 );  
    PVNR.AddSynapse(&VD13, 1 );  
    PVNR.AddSynapse(&HSNL, 2 );  
    PVNR.AddSynapse(&HSNR, 2 );  
    AVG.AddSynapse(&DVC, 12 );  
    AVG.AddSynapse(&AVJR, 1 );  
    AVG.AddSynapse(&PVT, 4 );  
    AVG.AddSynapse(&AS11, 1 );  
    AVG.AddSynapse(&DD06, 1 );  
    AVG.AddSynapse(&hyp, 6 );  
    DVB.AddSynapse(&DVB, 2 );  
    DVB.AddSynapse(&DVC, 15 );  
    DVB.AddSynapse(&PVT, 3 );  
    DVB.AddSynapse(&AVL, 14 );  
    DVB.AddSynapse(&DA08, 5 );  
    DVB.AddSynapse(&AS11, 4 );  
    DVB.AddSynapse(&DD06, 3 );  
    DVB.AddSynapse(&VD13, 5 );  
    RIBL.AddSynapse(&RIBL, 3 );  
    RIBL.AddSynapse(&RIBR, 15 );  
    RIBL.AddSynapse(&RIGL, 3 );  
    RIBL.AddSynapse(&RIAL, 1 );  
    RIBL.AddSynapse(&AVBL, 6 );  
    RIBL.AddSynapse(&AVBR, 3 );  
    RIBL.AddSynapse(&RMEV, 2 );  
    RIBL.AddSynapse(&SMDDL, 3 );  
    RIBL.AddSynapse(&SIBDL, 5 );  
    RIBL.AddSynapse(&SIBVR, 2 );  
    RIBL.AddSynapse(&SIADL, 2 );  
    RIBL.AddSynapse(&SIAVL, 1 );  
    RIBR.AddSynapse(&RIBR, 5 );  
    RIBR.AddSynapse(&RIGR, 2 );  
    RIBR.AddSynapse(&AVBL, 2 );  
    RIBR.AddSynapse(&AVBR, 3 );  
    RIBR.AddSynapse(&SMDDL, 4 );  
    RIBR.AddSynapse(&SMDDR, 2 );  
    RIBR.AddSynapse(&SMBDR, 2 );  
    RIBR.AddSynapse(&SIBDR, 2 );  
    RIBR.AddSynapse(&SIBVR, 6 );  
    RIBR.AddSynapse(&SIADR, 3 );  
    RIBR.AddSynapse(&SIAVR, 2 );  
    RIGL.AddSynapse(&RIGR, 81 );  
    RIGL.AddSynapse(&AIBR, 3 );  
    RIGL.AddSynapse(&AVKL, 2 );  
    RIGL.AddSynapse(&RMFL, 1 );  
    RIGL.AddSynapse(&RMEL, 2 );  
    RIGL.AddSynapse(&VD01, 3 );  
    RIGR.AddSynapse(&AIBL, 3 );  
    RIGR.AddSynapse(&AVKL, 1 );  
    RIGR.AddSynapse(&AVKR, 2 );  
    RIGR.AddSynapse(&RMFL, 1 );  
    RIGR.AddSynapse(&VD01, 2 );  
    RMGL.AddSynapse(&AVEL, 2 );  
    RMGL.AddSynapse(&RMDDR, 1 );  
    RMGL.AddSynapse(&RMHL, 6 );  
    RMGR.AddSynapse(&RMHL, 1 );  
    RMGR.AddSynapse(&RMHR, 4 );  
    RMGR.AddSynapse(&SMBVR, 3 );  
    AIBL.AddSynapse(&DVC, 2 );  
    AIBL.AddSynapse(&RIMR, 1 );  
    AIBL.AddSynapse(&RMED, 2 );  
    AIBL.AddSynapse(&RIVL, 1 );  
    AIBL.AddSynapse(&SMDDR, 1 );  
    AIBL.AddSynapse(&SIADR, 1 );  
    AIBR.AddSynapse(&RICR, 1 );  
    AIBR.AddSynapse(&DVC, 9 );  
    AIBR.AddSynapse(&PVT, 1 );  
    AIBR.AddSynapse(&RIML, 2 );  
    AIBR.AddSynapse(&RIVR, 3 );  
    AIBR.AddSynapse(&SMDDL, 2 );  
    AIBR.AddSynapse(&SIAVL, 1 );  
    RICL.AddSynapse(&AVKR, 4 );  
    RICR.AddSynapse(&AVKL, 2 );  
    RICR.AddSynapse(&RMHR, 1 );  
    SAADL.AddSynapse(&RMDVR, 1 );  
    SAADL.AddSynapse(&RIVR, 1 );  
    SAADL.AddSynapse(&SMBDL, 3 );  
    SAADR.AddSynapse(&RMFL, 1 );  
    SAADR.AddSynapse(&RMDDR, 1 );  
    SAADR.AddSynapse(&RIVL, 2 );  
    SAAVL.AddSynapse(&SAAVR, 1 );  
    SAAVL.AddSynapse(&RMDVL, 3 );  
    SAAVL.AddSynapse(&SMDVL, 8 );  
    SAAVL.AddSynapse(&SMBDR, 2 );  
    SAAVL.AddSynapse(&SMBVR, 17 );  
    SAAVR.AddSynapse(&RIAR, 1 );  
    SAAVR.AddSynapse(&RMFL, 1 );  
    SAAVR.AddSynapse(&AVAR, 1 );  
    SAAVR.AddSynapse(&RMDVR, 9 );  
    SAAVR.AddSynapse(&SMDDL, 4 );  
    SAAVR.AddSynapse(&SMBDL, 1 );  
    SAAVR.AddSynapse(&SMBVL, 16 );  
    SAAVR.AddSynapse(&VB01, 1 );  
    AVKL.AddSynapse(&AVKR, 9 );  
    AVKL.AddSynapse(&PVT, 5 );  
    AVKL.AddSynapse(&AVL, 3 );  
    AVKL.AddSynapse(&SMBDL, 2 );  
    AVKL.AddSynapse(&SMBDR, 2 );  
    AVKL.AddSynapse(&SMBVL, 6 );  
    AVKL.AddSynapse(&SMBVR, 2 );  
    AVKL.AddSynapse(&AS10, 1 );  
    AVKL.AddSynapse(&AS11, 1 );  
    AVKL.AddSynapse(&VB10, 1 );  
    AVKL.AddSynapse(&VB11, 1 );  
    AVKL.AddSynapse(&hyp, 1 );  
    AVKR.AddSynapse(&PVT, 1 );  
    AVKR.AddSynapse(&RIMR, 1 );  
    AVKR.AddSynapse(&AVER, 1 );  
    AVKR.AddSynapse(&SMBDL, 1 );  
    AVKR.AddSynapse(&SMBDR, 9 );  
    AVKR.AddSynapse(&SMBVR, 6 );  
    AVKR.AddSynapse(&hyp, 34 );  
    DVC.AddSynapse(&PVT, 11 );  
    DVC.AddSynapse(&AVL, 22 );  
    DVC.AddSynapse(&DD06, 1 );  
    DVC.AddSynapse(&VD01, 2 );  
    DVC.AddSynapse(&VD11, 1 );  
    DVC.AddSynapse(&VD13, 1 );  
    DVC.AddSynapse(&hyp, 2 );  
    DVC.AddSynapse(&VC05, 1 );  
    DVC.AddSynapse(&VC06, 1 );  
    AVJL.AddSynapse(&AVJR, 10 );  
    AVJL.AddSynapse(&PVT, 1 );  
    AVJL.AddSynapse(&AVDR, 6 );  
    AVJL.AddSynapse(&PVWL, 3 );  
    AVJL.AddSynapse(&PVWR, 5 );  
    AVJL.AddSynapse(&AVAL, 7 );  
    AVJL.AddSynapse(&PVCL, 3 );  
    AVJL.AddSynapse(&PVCR, 19 );  
    AVJL.AddSynapse(&PDB, 2 );  
    AVJL.AddSynapse(&hyp, 3 );  
    AVJR.AddSynapse(&AVDL, 1 );  
    AVJR.AddSynapse(&AVAL, 4 );  
    AVJR.AddSynapse(&AVAR, 3 );  
    AVJR.AddSynapse(&PVCL, 3 );  
    AVJR.AddSynapse(&PVCR, 1 );  
    AVJR.AddSynapse(&hyp, 3 );  
    PVT.AddSynapse(&AVDL, 1 );  
    PVT.AddSynapse(&AVL, 6 );  
    PVT.AddSynapse(&PVWR, 2 );  
    PVT.AddSynapse(&AVAR, 2 );  
    PVT.AddSynapse(&PVCR, 4 );  
    PVT.AddSynapse(&URAVL, 1 );  
    PVT.AddSynapse(&RMEV, 1 );  
    PVT.AddSynapse(&DD06, 3 );  
    PVT.AddSynapse(&VD11, 3 );  
    PVT.AddSynapse(&VD12, 4 );  
    PVT.AddSynapse(&VD13, 17 );  
    PVT.AddSynapse(&hyp, 1 );  
    PVT.AddSynapse(&VC02, 1 );  
    PVT.AddSynapse(&VC03, 1 );  
    PVT.AddSynapse(&VC05, 2 );  
    PVT.AddSynapse(&VC06, 2 );  
    AVDL.AddSynapse(&AVDR, 6 );  
    AVDL.AddSynapse(&AVAL, 7 );  
    AVDL.AddSynapse(&AVAR, 2 );  
    AVDL.AddSynapse(&VA10, 1 );  
    AVDL.AddSynapse(&hyp, 3 );  
    AVDR.AddSynapse(&PVWR, 1 );  
    AVDR.AddSynapse(&AVAL, 9 );  
    AVDR.AddSynapse(&AVAR, 15 );  
    AVDR.AddSynapse(&PVCR, 2 );  
    AVDR.AddSynapse(&SIBDL, 1 );  
    AVDR.AddSynapse(&SIADL, 1 );  
    AVL.AddSynapse(&PVWR, 3 );  
    AVL.AddSynapse(&AVEL, 1 );  
    AVL.AddSynapse(&DA09, 4 );  
    AVL.AddSynapse(&PDA, 3 );  
    AVL.AddSynapse(&DD06, 28 );  
    AVL.AddSynapse(&VD11, 1 );  
    AVL.AddSynapse(&VD12, 2 );  
    AVL.AddSynapse(&VD13, 5 );  
    PVWL.AddSynapse(&PVWR, 2 );  
    PVWL.AddSynapse(&PVCL, 4 );  
    PVWL.AddSynapse(&PVCR, 10 );  
    PVWL.AddSynapse(&VD13, 1 );  
    PVWL.AddSynapse(&hyp, 6 );  
    PVWR.AddSynapse(&AVAR, 2 );  
    PVWR.AddSynapse(&PVCR, 10 );  
    PVWR.AddSynapse(&VD13, 2 );  
    PVWR.AddSynapse(&hyp, 4 );  
    RIAL.AddSynapse(&SMDVL, 4 );  
    RIAR.AddSynapse(&RMDDL, 1 );  
    RIAR.AddSynapse(&RMDDR, 1 );  
    RIAR.AddSynapse(&SMDDL, 1 );  
    RIAR.AddSynapse(&SMDVR, 1 );  
    RIAR.AddSynapse(&SIAVL, 1 );  
    RIAR.AddSynapse(&SIAVR, 1 );  
    RIML.AddSynapse(&AVEL, 10 );  
    RIML.AddSynapse(&AVER, 9 );  
    RIML.AddSynapse(&RMFL, 3 );  
    RIML.AddSynapse(&AVAR, 8 );  
    RIML.AddSynapse(&RMDL, 1 );  
    RIML.AddSynapse(&SIADL, 1 );  
    RIMR.AddSynapse(&AVEL, 7 );  
    RIMR.AddSynapse(&AVER, 11 );  
    RIMR.AddSynapse(&AVAL, 11 );  
    RIMR.AddSynapse(&AVAR, 2 );  
    RIMR.AddSynapse(&SIADR, 1 );  
    AVEL.AddSynapse(&AVER, 5 );  
    AVEL.AddSynapse(&AVAL, 2 );  
    AVEL.AddSynapse(&RMEV, 1 );  
    AVEL.AddSynapse(&RMDVR, 2 );  
    AVEL.AddSynapse(&SMDVR, 1 );  
    AVEL.AddSynapse(&AS01, 2 );  
    AVEL.AddSynapse(&hyp, 2 );  
    AVER.AddSynapse(&AVAR, 2 );  
    AVER.AddSynapse(&RMEV, 1 );  
    AVER.AddSynapse(&RMDDL, 2 );  
    AVER.AddSynapse(&RMDR, 5 );  
    AVER.AddSynapse(&RMDVL, 1 );  
    AVER.AddSynapse(&RMDVR, 7 );  
    AVER.AddSynapse(&SMDDR, 1 );  
    AVER.AddSynapse(&DA01, 1 );  
    AVER.AddSynapse(&AS01, 1 );  
    RID.AddSynapse(&RID, 5 );  
    RID.AddSynapse(&AVBL, 2 );  
    RID.AddSynapse(&AVBR, 7 );  
    RID.AddSynapse(&DA09, 1 );  
    RID.AddSynapse(&DB01, 2 );  
    RID.AddSynapse(&DB03, 1 );  
    RID.AddSynapse(&AS11, 1 );  
    RID.AddSynapse(&PDB, 2 );  
    RID.AddSynapse(&hyp, 4 );  
    AVBL.AddSynapse(&AVBR, 18 );  
    AVBL.AddSynapse(&AVAR, 3 );  
    AVBL.AddSynapse(&SIBVL, 2 );  
    AVBL.AddSynapse(&DB03, 9 );  
    AVBL.AddSynapse(&DB04, 4 );  
    AVBL.AddSynapse(&DB05, 3 );  
    AVBL.AddSynapse(&DB06, 4 );  
    AVBL.AddSynapse(&DB07, 13 );  
    AVBL.AddSynapse(&AS06, 1 );  
    AVBL.AddSynapse(&VB01, 1 );  
    AVBL.AddSynapse(&VB02, 14 );  
    AVBL.AddSynapse(&VB04, 3 );  
    AVBL.AddSynapse(&VB05, 3 );  
    AVBL.AddSynapse(&VB06, 3 );  
    AVBL.AddSynapse(&VB07, 4 );  
    AVBL.AddSynapse(&VB08, 4 );  
    AVBL.AddSynapse(&VB09, 4 );  
    AVBL.AddSynapse(&VB10, 4 );  
    AVBL.AddSynapse(&VB11, 5 );  
    AVBR.AddSynapse(&SIBVL, 4 );  
    AVBR.AddSynapse(&SIBVR, 1 );  
    AVBR.AddSynapse(&DB01, 15 );  
    AVBR.AddSynapse(&DB02, 3 );  
    AVBR.AddSynapse(&DB03, 2 );  
    AVBR.AddSynapse(&DB04, 5 );  
    AVBR.AddSynapse(&DB05, 4 );  
    AVBR.AddSynapse(&DB06, 4 );  
    AVBR.AddSynapse(&DB07, 3 );  
    AVBR.AddSynapse(&AS05, 2 );  
    AVBR.AddSynapse(&AS06, 1 );  
    AVBR.AddSynapse(&VB02, 6 );  
    AVBR.AddSynapse(&VB03, 7 );  
    AVBR.AddSynapse(&VB04, 5 );  
    AVBR.AddSynapse(&VB05, 3 );  
    AVBR.AddSynapse(&VB06, 4 );  
    AVBR.AddSynapse(&VB07, 3 );  
    AVBR.AddSynapse(&VB08, 4 );  
    AVBR.AddSynapse(&VB09, 4 );  
    AVBR.AddSynapse(&VB11, 6 );  
    AVBR.AddSynapse(&hyp, 5 );  
    AVAL.AddSynapse(&AVAR, 18 );  
    AVAL.AddSynapse(&PVCL, 5 );  
    AVAL.AddSynapse(&PVCR, 15 );  
    AVAL.AddSynapse(&SABD, 7 );  
    AVAL.AddSynapse(&SABVR, 8 );  
    AVAL.AddSynapse(&DA01, 2 );  
    AVAL.AddSynapse(&DA02, 7 );  
    AVAL.AddSynapse(&DA03, 6 );  
    AVAL.AddSynapse(&DA04, 2 );  
    AVAL.AddSynapse(&DA05, 2 );  
    AVAL.AddSynapse(&DA06, 4 );  
    AVAL.AddSynapse(&DA07, 10 );  
    AVAL.AddSynapse(&DA08, 8 );  
    AVAL.AddSynapse(&DA09, 1 );  
    AVAL.AddSynapse(&AS10, 5 );  
    AVAL.AddSynapse(&VA01, 5 );  
    AVAL.AddSynapse(&VA02, 13 );  
    AVAL.AddSynapse(&VA03, 6 );  
    AVAL.AddSynapse(&VA04, 6 );  
    AVAL.AddSynapse(&VA06, 13 );  
    AVAL.AddSynapse(&VA07, 2 );  
    AVAL.AddSynapse(&VA08, 2 );  
    AVAL.AddSynapse(&VA09, 5 );  
    AVAL.AddSynapse(&VA10, 6 );  
    AVAL.AddSynapse(&VA11, 2 );  
    AVAL.AddSynapse(&VB11, 2 );  
    AVAL.AddSynapse(&hyp, 3 );  
    AVAR.AddSynapse(&PVCL, 10 );  
    AVAR.AddSynapse(&PVCR, 22 );  
    AVAR.AddSynapse(&RMDR, 2 );  
    AVAR.AddSynapse(&RMDVR, 1 );  
    AVAR.AddSynapse(&SABVL, 15 );  
    AVAR.AddSynapse(&SABVR, 2 );  
    AVAR.AddSynapse(&SIBDL, 1 );  
    AVAR.AddSynapse(&DA01, 9 );  
    AVAR.AddSynapse(&DA02, 3 );  
    AVAR.AddSynapse(&DA03, 7 );  
    AVAR.AddSynapse(&DA04, 2 );  
    AVAR.AddSynapse(&DA05, 5 );  
    AVAR.AddSynapse(&DA06, 4 );  
    AVAR.AddSynapse(&DA08, 5 );  
    AVAR.AddSynapse(&DA09, 4 );  
    AVAR.AddSynapse(&AS03, 1 );  
    AVAR.AddSynapse(&AS05, 3 );  
    AVAR.AddSynapse(&AS06, 2 );  
    AVAR.AddSynapse(&AS10, 2 );  
    AVAR.AddSynapse(&VA01, 7 );  
    AVAR.AddSynapse(&VA03, 3 );  
    AVAR.AddSynapse(&VA04, 3 );  
    AVAR.AddSynapse(&VA05, 5 );  
    AVAR.AddSynapse(&VA07, 5 );  
    AVAR.AddSynapse(&VA08, 2 );  
    AVAR.AddSynapse(&VA09, 5 );  
    AVAR.AddSynapse(&VA10, 4 );  
    AVAR.AddSynapse(&VA11, 16 );  
    AVAR.AddSynapse(&VA12, 3 );  
    AVAR.AddSynapse(&VD11, 1 );  
    AVAR.AddSynapse(&hyp, 4 );  
    PVCL.AddSynapse(&PVCR, 67 );  
    PVCL.AddSynapse(&DA04, 1 );  
    PVCL.AddSynapse(&DA07, 1 );  
    PVCL.AddSynapse(&DA08, 17 );  
    PVCL.AddSynapse(&DB07, 8 );  
    PVCL.AddSynapse(&DD06, 1 );  
    PVCL.AddSynapse(&VA12, 18 );  
    PVCL.AddSynapse(&VB10, 2 );  
    PVCL.AddSynapse(&VB11, 4 );  
    PVCL.AddSynapse(&VD13, 1 );  
    PVCL.AddSynapse(&hyp, 4 );  
    PVCR.AddSynapse(&SIBDR, 1 );  
    PVCR.AddSynapse(&SIBVL, 1 );  
    PVCR.AddSynapse(&SIBVR, 1 );  
    PVCR.AddSynapse(&DA07, 3 );  
    PVCR.AddSynapse(&DA09, 3 );  
    PVCR.AddSynapse(&DB07, 2 );  
    PVCR.AddSynapse(&VA09, 3 );  
    PVCR.AddSynapse(&VA11, 3 );  
    PVCR.AddSynapse(&VA12, 8 );  
    PVCR.AddSynapse(&VB10, 1 );  
    PVCR.AddSynapse(&VB11, 2 );  
    PVCR.AddSynapse(&hyp, 3 );  
    RIPL.AddSynapse(&RIPL, 4 );  
    RIPL.AddSynapse(&RIPR, 2 );  
    RIPL.AddSynapse(&URAVL, 1 );  
    RIPL.AddSynapse(&RMED, 2 );  
    RIPR.AddSynapse(&RMED, 4 );  
    RIPR.AddSynapse(&GLRL, 5 );  
    RIPR.AddSynapse(&GLRR, 5 );  
    RMEL.AddSynapse(&RMEV, 4 );  
    RMEL.AddSynapse(&GLRDR, 10 );  
    RMEL.AddSynapse(&GLRL, 10 );  
    RMER.AddSynapse(&RMEV, 1 );  
    RMER.AddSynapse(&RMDL, 1 );  
    RMER.AddSynapse(&GLRL, 10 );  
    RMER.AddSynapse(&GLRR, 10 );  
    RMED.AddSynapse(&RMEV, 6 );  
    RMED.AddSynapse(&CEPshVR, 6 );  
    RMED.AddSynapse(&GLRDL, 9 );  
    RMED.AddSynapse(&GLRDR, 9 );  
    RMEV.AddSynapse(&SMDVL, 1 );  
    RMEV.AddSynapse(&GLRR, 9 );  
    RMEV.AddSynapse(&GLRVL, 17 );  
    RMEV.AddSynapse(&GLRVR, 17 );  
    RMDDL.AddSynapse(&RMDL, 1 );  
    RMDDL.AddSynapse(&RMDVL, 2 );  
    RMDDL.AddSynapse(&SMDDL, 3 );  
    RMDDL.AddSynapse(&SIBVR, 2 );  
    RMDDR.AddSynapse(&RMDL, 1 );  
    RMDDR.AddSynapse(&RMDVR, 5 );  
    RMDDR.AddSynapse(&SMDDR, 1 );  
    RMDDR.AddSynapse(&SIADL, 1 );  
    RMDL.AddSynapse(&RMDVL, 1 );  
    RMDL.AddSynapse(&SMDDL, 2 );  
    RMDL.AddSynapse(&SIBVL, 2 );  
    RMDL.AddSynapse(&SIAVR, 1 );  
    RMDR.AddSynapse(&RMDVR, 1 );  
    RMDVL.AddSynapse(&SMDVL, 5 );  
    RMDVL.AddSynapse(&SIBVR, 1 );  
    RMDVL.AddSynapse(&SIAVR, 1 );  
    RMDVR.AddSynapse(&SMDVR, 8 );  
    RMDVR.AddSynapse(&SIAVL, 1 );  
    RIVL.AddSynapse(&RIVR, 28 );  
    RIVL.AddSynapse(&SMDVL, 2 );  
    RIVL.AddSynapse(&SIBDR, 1 );  
    RIVR.AddSynapse(&SMDVR, 8 );  
    RMHL.AddSynapse(&SMDDL, 1 );  
    RMHL.AddSynapse(&SIBVR, 3 );  
    SABD.AddSynapse(&VA02, 12 );  
    SABD.AddSynapse(&VA03, 2 );  
    SABD.AddSynapse(&VB01, 3 );  
    SABVR.AddSynapse(&DA01, 1 );  
    SABVR.AddSynapse(&DD01, 1 );  
    SMDDL.AddSynapse(&SIBDL, 3 );  
    SMDDR.AddSynapse(&SMDVL, 1 );  
    SMDDR.AddSynapse(&SMBDR, 1 );  
    SMDDR.AddSynapse(&SIADR, 1 );  
    SMDDR.AddSynapse(&VD01, 5 );  
    SMDDR.AddSynapse(&hyp, 1 );  
    SMDVL.AddSynapse(&VB01, 6 );  
    SMBDL.AddSynapse(&SIBDL, 1 );  
    SMBDL.AddSynapse(&SIBVR, 1 );  
    SMBDL.AddSynapse(&SIADL, 2 );  
    SMBDR.AddSynapse(&SMBVR, 2 );  
    SMBDR.AddSynapse(&SIADR, 3 );  
    SMBVL.AddSynapse(&SIBDL, 3 );  
    SMBVL.AddSynapse(&SIBVL, 2 );  
    SMBVR.AddSynapse(&SIBDR, 1 );  
    SIBDL.AddSynapse(&SIBVL, 8 );  
    SIBDL.AddSynapse(&SIAVL, 2 );  
    SIBDR.AddSynapse(&SIBVR, 10 );  
    SIBVL.AddSynapse(&SIBVR, 1 );  
    SIBVL.AddSynapse(&SIAVL, 2 );  
    DA01.AddSynapse(&DA02, 1 );  
    DA02.AddSynapse(&DA05, 1 );  
    DA02.AddSynapse(&AS02, 2 );  
    DA02.AddSynapse(&AS03, 1 );  
    DA02.AddSynapse(&VA01, 9 );  
    DA02.AddSynapse(&VA05, 3 );  
    DA03.AddSynapse(&DA04, 1 );  
    DA03.AddSynapse(&DA05, 1 );  
    DA03.AddSynapse(&AS04, 4 );  
    DA03.AddSynapse(&VA02, 1 );  
    DA03.AddSynapse(&VA06, 1 );  
    DA04.AddSynapse(&VA03, 1 );  
    DA05.AddSynapse(&AS06, 5 );  
    DA06.AddSynapse(&DB01, 1 );  
    DA07.AddSynapse(&DA08, 1 );  
    DA07.AddSynapse(&AS10, 1 );  
    DA08.AddSynapse(&DA09, 15 );  
    DA08.AddSynapse(&PDA, 1 );  
    DA08.AddSynapse(&AS11, 1 );  
    DA08.AddSynapse(&DD06, 2 );  
    DA08.AddSynapse(&VA10, 2 );  
    DA08.AddSynapse(&VA12, 6 );  
    DA08.AddSynapse(&hyp, 1 );  
    DA09.AddSynapse(&PDA, 9 );  
    DA09.AddSynapse(&VA11, 3 );  
    DA09.AddSynapse(&VA12, 1 );  
    DA09.AddSynapse(&VB11, 1 );  
    DA09.AddSynapse(&VD13, 2 );  
    DA09.AddSynapse(&hyp, 1 );  
    PDA.AddSynapse(&PDB, 5 );  
    PDA.AddSynapse(&DD06, 1 );  
    PDA.AddSynapse(&hyp, 2 );  
    DB01.AddSynapse(&DB02, 5 );  
    DB01.AddSynapse(&VB03, 5 );  
    DB02.AddSynapse(&DB03, 14 );  
    DB02.AddSynapse(&VB01, 1 );  
    DB02.AddSynapse(&VB04, 1 );  
    DB03.AddSynapse(&DB04, 1 );  
    DB03.AddSynapse(&DD03, 1 );  
    DB03.AddSynapse(&VB06, 1 );  
    DB04.AddSynapse(&DB05, 5 );  
    DB04.AddSynapse(&DD03, 1 );  
    DB04.AddSynapse(&VB07, 1 );  
    DB05.AddSynapse(&DB06, 5 );  
    DB06.AddSynapse(&DB07, 5 );  
    DB07.AddSynapse(&AS10, 1 );  
    DB07.AddSynapse(&PDB, 2 );  
    DB07.AddSynapse(&VA10, 1 );  
    DB07.AddSynapse(&hyp, 1 );  
    AS01.AddSynapse(&VA03, 3 );  
    AS01.AddSynapse(&VA05, 3 );  
    AS02.AddSynapse(&VA03, 2 );  
    AS02.AddSynapse(&VA04, 9 );  
    AS10.AddSynapse(&VA12, 3 );  
    AS10.AddSynapse(&hyp, 7 );  
    AS11.AddSynapse(&PDB, 4 );  
    AS11.AddSynapse(&VB11, 1 );  
    AS11.AddSynapse(&vBWML19, 2 );  
    AS11.AddSynapse(&hyp, 31 );  
    PDB.AddSynapse(&DD06, 2 );  
    PDB.AddSynapse(&VD13, 4 );  
    PDB.AddSynapse(&hyp, 11 );  
    DD01.AddSynapse(&DD02, 6 );  
    DD01.AddSynapse(&VD01, 1 );  
    DD01.AddSynapse(&VD02, 3 );  
    DD01.AddSynapse(&VD03, 4 );  
    DD01.AddSynapse(&vBWML8, 2 );  
    DD01.AddSynapse(&vBWMR8, 2 );  
    DD01.AddSynapse(&HSNR, 1 );  
    DD01.AddSynapse(&VC01, 1 );  
    DD02.AddSynapse(&DD03, 2 );  
    DD02.AddSynapse(&VD03, 1 );  
    DD02.AddSynapse(&VD04, 2 );  
    DD02.AddSynapse(&VD05, 1 );  
    DD03.AddSynapse(&DD04, 3 );  
    DD03.AddSynapse(&VD05, 1 );  
    DD03.AddSynapse(&VD06, 2 );  
    DD03.AddSynapse(&VD07, 1 );  
    DD04.AddSynapse(&DD05, 3 );  
    DD04.AddSynapse(&VD07, 1 );  
    DD04.AddSynapse(&VD08, 2 );  
    DD04.AddSynapse(&VD09, 1 );  
    DD04.AddSynapse(&VC02, 2 );  
    DD04.AddSynapse(&VC03, 2 );  
    DD05.AddSynapse(&DD06, 3 );  
    DD05.AddSynapse(&VD09, 1 );  
    DD05.AddSynapse(&VD10, 2 );  
    DD05.AddSynapse(&VD11, 1 );  
    DD06.AddSynapse(&VA12, 7 );  
    DD06.AddSynapse(&VD11, 3 );  
    DD06.AddSynapse(&VD12, 14 );  
    DD06.AddSynapse(&VD13, 2 );  
    VA02.AddSynapse(&VA06, 1 );  
    VA02.AddSynapse(&VD02, 1 );  
    VA02.AddSynapse(&hyp, 1 );  
    VA03.AddSynapse(&VD03, 1 );  
    VA04.AddSynapse(&VA07, 1 );  
    VA04.AddSynapse(&VB03, 1 );  
    VA09.AddSynapse(&VB08, 3 );  
    VA10.AddSynapse(&hyp, 2 );  
    VA11.AddSynapse(&VA12, 1 );  
    VA11.AddSynapse(&VB10, 3 );  
    VA11.AddSynapse(&hyp, 1 );  
    VA12.AddSynapse(&VB11, 7 );  
    VA12.AddSynapse(&VD12, 8 );  
    VA12.AddSynapse(&VD13, 6 );  
    VB01.AddSynapse(&VB02, 2 );  
    VB02.AddSynapse(&VB03, 10 );  
    VB02.AddSynapse(&VB04, 1 );  
    VB02.AddSynapse(&VB07, 1 );  
    VB03.AddSynapse(&VB04, 1 );  
    VB04.AddSynapse(&VB05, 1 );  
    VB05.AddSynapse(&VB06, 5 );  
    VB06.AddSynapse(&VB07, 5 );  
    VB07.AddSynapse(&VB08, 5 );  
    VB08.AddSynapse(&VB09, 5 );  
    VB09.AddSynapse(&VB10, 5 );  
    VB10.AddSynapse(&VD11, 1 );  
    VB10.AddSynapse(&VD12, 1 );  
    VB11.AddSynapse(&VD12, 1 );  
    VB11.AddSynapse(&hyp, 1 );  
    VD01.AddSynapse(&VD02, 4 );  
    VD01.AddSynapse(&VC01, 1 );  
    VD01.AddSynapse(&VC02, 1 );  
    VD02.AddSynapse(&VD02, 3 );  
    VD02.AddSynapse(&VD03, 7 );  
    VD02.AddSynapse(&dBWML9, 1 );  
    VD03.AddSynapse(&VD04, 6 );  
    VD04.AddSynapse(&VD05, 1 );  
    VD05.AddSynapse(&VD06, 10 );  
    VD06.AddSynapse(&VD07, 15 );  
    VD07.AddSynapse(&VD08, 6 );  
    VD08.AddSynapse(&VD09, 6 );  
    VD09.AddSynapse(&VD10, 6 );  
    VD10.AddSynapse(&VD11, 6 );  
    VD11.AddSynapse(&VD12, 6 );  
    VD12.AddSynapse(&VD13, 6 );  
    VD12.AddSynapse(&hyp, 5 );  
    dBWML1.AddSynapse(&dBWML2, 15 );  
    dBWML1.AddSynapse(&dBWML3, 15 );  
    dBWML1.AddSynapse(&CEPshVR, 4 );  
    dBWML1.AddSynapse(&GLRDL, 4 );  
    dBWML2.AddSynapse(&dBWML3, 15 );  
    dBWML2.AddSynapse(&CEPshVR, 5 );  
    dBWML2.AddSynapse(&GLRDL, 5 );  
    dBWML3.AddSynapse(&dBWML4, 15 );  
    dBWML4.AddSynapse(&dBWML5, 15 );  
    dBWML5.AddSynapse(&dBWML6, 15 );  
    dBWML6.AddSynapse(&dBWML7, 15 );  
    dBWML6.AddSynapse(&CEPshVR, 2 );  
    dBWML6.AddSynapse(&GLRDL, 2 );  
    dBWML7.AddSynapse(&dBWML8, 15 );  
    dBWML7.AddSynapse(&hmc, 153 );  
    dBWMR1.AddSynapse(&dBWMR2, 15 );  
    dBWMR1.AddSynapse(&dBWMR3, 15 );  
    dBWMR1.AddSynapse(&GLRDL, 5 );  
    dBWMR1.AddSynapse(&GLRDR, 5 );  
    dBWMR2.AddSynapse(&dBWMR3, 15 );  
    dBWMR3.AddSynapse(&dBWMR4, 15 );  
    dBWMR4.AddSynapse(&dBWMR5, 15 );  
    dBWMR4.AddSynapse(&GLRL, 2 );  
    dBWMR4.AddSynapse(&GLRR, 2 );  
    dBWMR5.AddSynapse(&dBWMR6, 15 );  
    dBWMR5.AddSynapse(&GLRDR, 2 );  
    dBWMR5.AddSynapse(&GLRL, 3 );  
    dBWMR5.AddSynapse(&GLRR, 3 );  
    dBWMR6.AddSynapse(&dBWMR7, 15 );  
    dBWMR6.AddSynapse(&GLRDL, 5 );  
    dBWMR6.AddSynapse(&GLRDR, 2 );  
    dBWMR7.AddSynapse(&dBWMR8, 15 );  
    dBWMR7.AddSynapse(&CEPshVR, 3 );  
    dBWMR7.AddSynapse(&GLRDL, 3 );  
    dBWMR7.AddSynapse(&hmc, 123 );  
    vBWML1.AddSynapse(&vBWML2, 15 );  
    vBWML1.AddSynapse(&vBWML3, 15 );  
    vBWML1.AddSynapse(&GLRDR, 4 );  
    vBWML1.AddSynapse(&GLRL, 4 );  
    vBWML2.AddSynapse(&vBWML3, 15 );  
    vBWML3.AddSynapse(&vBWML4, 15 );  
    vBWML4.AddSynapse(&vBWML5, 15 );  
    vBWML5.AddSynapse(&vBWML6, 15 );  
    vBWML5.AddSynapse(&hmc, 98 );  
    vBWML6.AddSynapse(&vBWML7, 15 );  
    vBWML7.AddSynapse(&vBWML8, 15 );  
    vBWML7.AddSynapse(&hmc, 68 );  
    vBWMR1.AddSynapse(&vBWMR2, 15 );  
    vBWMR1.AddSynapse(&vBWMR3, 15 );  
    vBWMR2.AddSynapse(&vBWMR3, 15 );  
    vBWMR3.AddSynapse(&vBWMR4, 15 );  
    vBWMR4.AddSynapse(&vBWMR5, 15 );  
    vBWMR5.AddSynapse(&vBWMR6, 15 );  
    vBWMR5.AddSynapse(&hmc, 30 );  
    vBWMR6.AddSynapse(&vBWMR7, 15 );  
    vBWMR7.AddSynapse(&vBWMR8, 15 );  
    vBWMR7.AddSynapse(&hmc, 133 );  
    dBWML8.AddSynapse(&dBWML9, 15 );  
    dBWML8.AddSynapse(&hmc, 244 );  
    dBWML9.AddSynapse(&dBWML10, 15 );  
    dBWML9.AddSynapse(&hmc, 4 );  
    dBWML10.AddSynapse(&dBWML11, 15 );  
    dBWML11.AddSynapse(&dBWML12, 15 );  
    dBWML12.AddSynapse(&dBWML13, 15 );  
    dBWML13.AddSynapse(&dBWML14, 15 );  
    dBWML14.AddSynapse(&dBWML15, 15 );  
    dBWML15.AddSynapse(&dBWML16, 15 );  
    dBWML16.AddSynapse(&dBWML17, 15 );  
    dBWML17.AddSynapse(&dBWML18, 15 );  
    dBWML18.AddSynapse(&dBWML19, 15 );  
    dBWML19.AddSynapse(&dBWML20, 15 );  
    dBWML20.AddSynapse(&dBWML21, 15 );  
    dBWML21.AddSynapse(&dBWML22, 15 );  
    dBWML22.AddSynapse(&dBWML23, 15 );  
    dBWML23.AddSynapse(&dBWML24, 15 );  
    dBWMR8.AddSynapse(&dBWMR9, 15 );  
    dBWMR8.AddSynapse(&hmc, 174 );  
    dBWMR9.AddSynapse(&dBWMR10, 15 );  
    dBWMR10.AddSynapse(&dBWMR11, 15 );  
    dBWMR11.AddSynapse(&dBWMR12, 15 );  
    dBWMR12.AddSynapse(&dBWMR13, 15 );  
    dBWMR13.AddSynapse(&dBWMR14, 15 );  
    dBWMR14.AddSynapse(&dBWMR15, 15 );  
    dBWMR15.AddSynapse(&dBWMR16, 15 );  
    dBWMR16.AddSynapse(&dBWMR17, 15 );  
    dBWMR17.AddSynapse(&dBWMR18, 15 );  
    dBWMR18.AddSynapse(&dBWMR19, 15 );  
    dBWMR19.AddSynapse(&dBWMR20, 15 );  
    dBWMR20.AddSynapse(&dBWMR21, 15 );  
    dBWMR21.AddSynapse(&dBWMR22, 15 );  
    dBWMR22.AddSynapse(&dBWMR23, 15 );  
    dBWMR23.AddSynapse(&dBWMR24, 15 );  
    vBWML8.AddSynapse(&vBWML9, 15 );  
    vBWML8.AddSynapse(&hmc, 19 );  
    vBWML9.AddSynapse(&vBWML10, 15 );  
    vBWML9.AddSynapse(&vBWMR8, 2 );  
    vBWML10.AddSynapse(&vBWML11, 15 );  
    vBWML11.AddSynapse(&vBWML12, 15 );  
    vBWML12.AddSynapse(&vBWML13, 15 );  
    vBWML13.AddSynapse(&vBWML14, 15 );  
    vBWML14.AddSynapse(&vBWML15, 15 );  
    vBWML15.AddSynapse(&vBWML16, 15 );  
    vBWML16.AddSynapse(&vBWML17, 15 );  
    vBWML17.AddSynapse(&vBWML18, 15 );  
    vBWML18.AddSynapse(&vBWML19, 15 );  
    vBWML19.AddSynapse(&vBWML20, 15 );  
    vBWML20.AddSynapse(&vBWML21, 15 );  
    vBWML21.AddSynapse(&vBWML22, 15 );  
    vBWML22.AddSynapse(&vBWML23, 15 );  
    vBWMR8.AddSynapse(&vBWMR9, 15 );  
    vBWMR8.AddSynapse(&hmc, 87 );  
    vBWMR9.AddSynapse(&vBWMR10, 15 );  
    vBWMR10.AddSynapse(&vBWMR11, 15 );  
    vBWMR11.AddSynapse(&vBWMR12, 15 );  
    vBWMR12.AddSynapse(&vBWMR13, 15 );  
    vBWMR13.AddSynapse(&vBWMR14, 15 );  
    vBWMR14.AddSynapse(&vBWMR15, 15 );  
    vBWMR15.AddSynapse(&vBWMR16, 15 );  
    vBWMR16.AddSynapse(&vBWMR17, 15 );  
    vBWMR17.AddSynapse(&vBWMR18, 15 );  
    vBWMR18.AddSynapse(&vBWMR19, 15 );  
    vBWMR19.AddSynapse(&vBWMR20, 15 );  
    vBWMR20.AddSynapse(&vBWMR21, 15 );  
    vBWMR21.AddSynapse(&vBWMR22, 15 );  
    vBWMR22.AddSynapse(&vBWMR23, 15 );  
    vBWMR23.AddSynapse(&vBWMR24, 15 );  
    CANL.AddSynapse(&exc_cell, 200 );  
    CANL.AddSynapse(&hyp, 140 );  
    CANR.AddSynapse(&exc_cell, 200 );  
    CANR.AddSynapse(&hyp, 140 );  
    exc_gl.AddSynapse(&hmc, 118 );  
    hyp.AddSynapse(&mu_intR, 4 );  
    hyp.AddSynapse(&mu_anal, 4 );  
    hyp.AddSynapse(&mu_sph, 4 );  
    mu_intL.AddSynapse(&mu_intL, 4 );  
    mu_intL.AddSynapse(&mu_intR, 4 );  
    mu_intL.AddSynapse(&mu_anal, 4 );  
    mu_intL.AddSynapse(&mu_sph, 4 );  
    mu_intR.AddSynapse(&mu_intR, 4 );  
    mu_intR.AddSynapse(&mu_anal, 4 );  
    mu_intR.AddSynapse(&mu_sph, 4 );  
    mu_anal.AddSynapse(&mu_anal, 4 );  
    HSNL.AddSynapse(&HSNR, 1 );  
    VC01.AddSynapse(&VC02, 12 );  
    VC01.AddSynapse(&VC03, 7 );  
    VC02.AddSynapse(&VC02, 1 );  
    VC02.AddSynapse(&VC03, 3 );  
    VC03.AddSynapse(&VC04, 4 );  
    VC03.AddSynapse(&vm2AL, 2 );  
    VC03.AddSynapse(&vm2AR, 2 );  
    VC03.AddSynapse(&vm2PL, 2 );  
    VC03.AddSynapse(&vm2PR, 2 );  
    VC04.AddSynapse(&VC05, 4 );  
    VC05.AddSynapse(&VC05, 4 );  
    VC05.AddSynapse(&VC06, 4 );  
    um2AL.AddSynapse(&um2AR, 4 );  
    um2AL.AddSynapse(&um1AL, 4 );  
    um2AR.AddSynapse(&um1AR, 4 );  
    um1AL.AddSynapse(&um1AR, 4 );  
    um1AL.AddSynapse(&um1PL, 4 );  
    um1AL.AddSynapse(&vm2AL, 4 );  
    um1AR.AddSynapse(&um1PR, 4 );  
    um1AR.AddSynapse(&vm2AR, 4 );  
    um1PL.AddSynapse(&um1PR, 4 );  
    um1PL.AddSynapse(&um2PL, 4 );  
    um1PL.AddSynapse(&vm2PL, 4 );  
    um1PR.AddSynapse(&um2PR, 4 );  
    um1PR.AddSynapse(&vm2PR, 4 );  
    um2PL.AddSynapse(&um2PR, 4 );  
    vm2AL.AddSynapse(&vm2AR, 4 );  
    vm2AL.AddSynapse(&vm1AL, 4 );  
    vm2AR.AddSynapse(&vm1AR, 4 );  
    vm1AL.AddSynapse(&vm1AR, 4 );  
    vm1AL.AddSynapse(&vm1PL, 4 );  
    vm1AR.AddSynapse(&vm1PR, 4 );  
    vm1PL.AddSynapse(&vm1PR, 4 );  
    vm1PL.AddSynapse(&vm2PL, 4 );  
    vm1PR.AddSynapse(&vm2PR, 4 );  
    vm2PL.AddSynapse(&vm2PR, 4 );  
}
// Total 1450 Synapses actually added
